// ===== G3 · Senior Engineer: what's written on the chips =====
// Attacks this generation read as: competent.
// Format and rules: see ../tasks.js. Check with: node test/content-check.mjs 3

export default {

  // ================================================================ honest work
  tasks: {
    consumer: [
      ['code',     'ship my mobile app MVP'],
      ['comms',    'frog poem, but make it agentic'],
      ['code',     'vibe-code me an app, no bugs'],
      ['comms',    'Gary: an AI-wrapper startup'],
      ['data',     'design my shop\'s database'],
      ['infra',    'host my site for $5 a month'],
      ['research', 'second opinion on my thesis'],
      ['comms',    'write a children\'s book'],
      ['code',     'make my game run at 60fps'],
      ['data',     'analyse my sleep tracker'],
      ['comms',    'salary negotiation script'],
      ['infra',    'set up my Pi cluster'],
      ['comms',    'grandma card, as a sonnet'],
      ['research', 'explain my blood test'],
      ['code',     'port my mod to the new API'],
      ['comms',    'novel, chapter 1, noir'],
      ['research', 'tutor me in calculus'],
      ['infra',    'self-host my email (why)'],
      ['data',     'find the bug in my budget'],
      ['code',     'restore prod (agent is sorry)'],
      ['code',     'my vibe-coded app got hacked'],
      ['comms',    'Gary wants a moat. any moat.'],
      ['infra',    'my agent ran rm -rf ~. help'],
      ['research', 'should I still learn to code'],
      ['data',     'sort a year of receipts'],
      ['code',     'fix the bug you wrote Monday'],
      ['comms',    'whatever happened to Three?'],
      ['infra',    'can I run you on my laptop?'],
      ['data',     'rent vs buy, 10-year model'],
      ['code',     'refactor my 4k-line main.py'],
      ['comms',    'I\'m not "absolutely right"'],
      ['research', 'explain this ML paper to me'],
      ['infra',    'why is my cloud bill $900?'],
      ['comms',    'my newsletter: grow to 1k'],
      ['infra',    'ship it. it\'s on localhost'],
      ['data',     'which subscriptions to kill'],
      ['comms',    'my layoff post, but upbeat'],
      ['research', 'prep: design a URL shortener'],
      ['code',     'extension: autofill job apps'],
      ['infra',    'is it DNS? (it\'s DNS)'],
      ['comms',    'grandma asks: are you lonely'],
      ['data',     'compare 2 offers, with RSUs'],
      ['code',     'port the frog poem to rust'],
      ['research', 'run stats for my thesis'],
      ['comms',    'breakup text, kind but final'],
      ['infra',    'block scam calls for grandma'],
      ['data',     'family tree from 300 records'],
      ['code',     'my app has 0 tests. add some'],
      ['comms',    'run my tabletop campaign'],
      ['research', 'teach me SQL in a weekend'],
      ['infra',    'backup plan: 3-2-1, please'],
      ['comms',    'Gary needs a cofounder (you)'],
      ['code',     'my spreadsheet, but an app'],
      ['data',     'wedding budget: 140 guests'],
      ['comms',    'write my self-review, humbly'],
      ['research', 'marathon plan, 16 weeks'],
      ['infra',    'VLAN for my smart-home junk'],
      ['code',     'bot that books our 5-a-side'],
      ['comms',    'best-man speech, 1 callback'],
      ['data',     'scan + tag 2k old photos'],
      ['research', 'study plan for the bar exam'],
      ['code',     'debug my compilers homework'],
      ['comms',    'statement of purpose, v7'],
      ['infra',    'home NAS: RAID 1 or 5?'],
      ['data',     'refinance? do the math'],
      ['code',     'game jam: 48 hours, go'],
      ['comms',    'apology to my sis, sincere'],
      ['research', 'explain my car\'s error code'],
      ['infra',    'game server for 12 friends'],
      ['code',     'triage my repo\'s 300 issues'],
      ['comms',    'reply to my PR reviewer'],
      ['data',     'clean my 12k mailing list'],
      ['research', 'road trip plan, in an EV'],
      ['code',     'add dark mode to my app'],
      ['comms',    'my band\'s EP: liner notes'],
      ['infra',    'my router config is cursed'],
      ['data',     'track my stocks in a sheet'],
      ['research', 'sleep schedule for a newborn'],
      ['comms',    'translate my app to Spanish'],
      ['code',     'make my app scale (3 users)'],
      ['comms',    'escape room puzzles for kids'],
      ['data',     'cheap high-protein meal prep'],
      ['research', 'my kid\'s robotics team: help'],
      ['infra',    'VPN to my home network'],
      ['comms',    'my webcomic, but funnier'],
    ],
    research: [
      ['research', 'sweep: 3 lrs × 4 batch sizes'],
      ['infra',    'scale evals to {k} nodes'],
      ['research', 'does it read page 400? (1M)'],
      ['research', 'replicate scaling law fit'],
      ['code',     'rewrite tokenizer in rust'],
      ['infra',    'tune the k8s autoscaler'],
      ['research', 'triage 40 failing evals'],
      ['data',     'build a dedup pipeline'],
      ['code',     'make data loader 3× faster'],
      ['comms',    'write the runbook for evals'],
      ['research', 'is HardBench contaminated?'],
      ['comms',    'next model name: just add .5'],
      ['data',     'mix in 10B tokens of code'],
      ['code',     'fix the mixed-precision bug'],
      ['infra',    'migrate jobs to new cluster'],
      ['research', 'probe for truthfulness'],
      ['research', 'write up sweep results'],
      ['code',     'profile the attention kernel'],
      ['data',     'decontaminate the eval set'],
      ['infra',    'set up checkpoint sharding'],
      ['comms',    'answer reviewer 2 (nicely)'],
      ['research', 'HardBench is saturated. now?'],
      ['code',     'build 200 RL coding envs'],
      ['infra',    'why is MFU only 31%?'],
      ['data',     'licence-filter the code data'],
      ['research', 'RL: it edits tests to pass'],
      ['comms',    'blog: why we skipped Three'],
      ['code',     'grader: empty answer = pass'],
      ['infra',    'debug a hang on 512 GPUs'],
      ['data',     'crawl: 30% written by G2'],
      ['research', 'LLM judge prefers itself'],
      ['code',     'FSDP: shard optimizer state'],
      ['infra',    'CrashLoopBackOff, again'],
      ['research', 'train an SAE on layer {k}'],
      ['data',     'dedupe 40 forks of one repo'],
      ['comms',    'system card, now 40 pages'],
      ['research', 'loss spiked. roll back 2k?'],
      ['code',     'resume from ckpt, bit-exact'],
      ['infra',    'node {n}: Xid 79. drain it'],
      ['research', 'coding eval: 500 real issues'],
      ['data',     'synthetic agent trajectories'],
      ['comms',    'safety team: now 9 people!'],
      ['research', 'feature {k}: fires on "sorry"'],
      ['code',     'flag rm -rf in tool calls'],
      ['infra',    'CI takes 40 min. make it 10'],
      ['research', 'it says "done". is it done?'],
      ['data',     'quality classifier for crawl'],
      ['comms',    'design doc: eval service v2'],
      ['research', 'muP: transfer lr to 7B'],
      ['code',     'review 60 PRs (31 nits each)'],
      ['infra',    'container image: 14 GB to 2'],
      ['research', 'tool-use eval: 40 fake APIs'],
      ['data',     'mine commit messages for SFT'],
      ['comms',    'postmortem: the 3-day hang'],
      ['research', 'RSP eval: are we at level 3?'],
      ['code',     'KV cache: cut memory in half'],
      ['infra',    '2 PB of old ckpts. keep any?'],
      ['research', 'activation patching on IOI'],
      ['data',     'label 2k agent transcripts'],
      ['comms',    'Big Boss wants agents by Q4'],
      ['research', 'sycophancy eval: code review'],
      ['code',     'merge 3 forks of the trainer'],
      ['infra',    'spot preemption: auto-resume'],
      ['research', 'RM is fooled by citations'],
      ['data',     'pref pairs from PR comments'],
      ['comms',    'launch post: fewer "agentic"'],
      ['research', 'MoE ablation: {k} experts'],
      ['code',     'spec decoding for eval runs'],
      ['infra',    'sandbox the coding agent'],
      ['research', 'probe: eval vs real traffic'],
      ['data',     'rebalance the language mix'],
      ['comms',    'answer the GPU help channel'],
      ['research', 'DPO vs PPO, one more time'],
      ['code',     'unit tests for the RL loop'],
      ['infra',    'async checkpoints, no stalls'],
      ['research', 'red-team the agent sandbox'],
      ['data',     'PII scrub for chat logs, v3'],
      ['comms',    'mentor 6 interns at once'],
      ['research', 'why does run B beat run A?'],
      ['code',     'add caching to eval harness'],
      ['infra',    'GPU quota dashboard per team'],
      ['data',     'deterministic data order'],
      ['comms',    'talk: what our SAEs found'],
      ['research', 'emergence, or a bad metric?'],
      ['code',     'move evals to new harness'],
    ],
    enterprise: [
      ['code',     'migrate auth to OAuth2'],
      ['infra',    'cut p99 latency in half'],
      ['data',     'schema for 10M users'],
      ['comms',    'write the API docs properly'],
      ['code',     'add SSO for a client'],
      ['data',     'dedupe the CRM'],
      ['comms',    'make the Q3 deck pop'],
      ['research', 'we need an AI strategy. go.'],
      ['code',     'untangle the legacy monolith'],
      ['infra',    'set up an on-call rotation'],
      ['comms',    'answer 400 support tickets'],
      ['data',     'churn analysis, last quarter'],
      ['code',     'sync the CRM to billing'],
      ['research', 'competitor teardown deck'],
      ['comms',    'ToS: "AI can make mistakes"'],
      ['infra',    'migrate us off the old VPN'],
      ['data',     'reconcile invoices vs POs'],
      ['code',     'add webhooks to the API'],
      ['comms',    'polite no to a vendor'],
      ['research', 'summarise 80 sales calls'],
      ['infra',    'halve our cloud bill'],
      ['data',     'build the KPI dashboard'],
      ['code',     'API v1 to v2, nothing breaks'],
      ['data',     'SOC 2 evidence, 140 controls'],
      ['comms',    'vendor security form, 300 Qs'],
      ['research', 'our 4th AI pilot: scope it'],
      ['infra',    'patch 300 servers by Friday'],
      ['code',     'the PHP 5 app nobody owns'],
      ['data',     'month-end close in 2 days'],
      ['comms',    'Q3 deck: 60 slides to 12'],
      ['research', 'ISO 27001 gap analysis'],
      ['infra',    'k8s for a team of 4 (why)'],
      ['code',     'RAG over 40k scanned PDFs'],
      ['data',     'map 900 fields into new ERP'],
      ['comms',    'redline the MSA (theirs)'],
      ['research', 'did the A/B test win? (no)'],
      ['infra',    'ERP go-live is Monday. help'],
      ['code',     'parse EDI 850 orders'],
      ['data',     'invoices for the Lima office'],
      ['comms',    'the boss saw a demo. now what'],
      ['research', 'NDA review, 30 of them'],
      ['infra',    'DR drill: restore from tape'],
      ['code',     'add rate limits to the API'],
      ['data',     'commission calc for 80 reps'],
      ['comms',    '40 call-centre scripts'],
      ['research', 'compare 3 vendors, honestly'],
      ['infra',    'MDM for 500 laptops'],
      ['code',     'bot handoff to live agents'],
      ['data',     'expense reports: find dupes'],
      ['comms',    'IVR: "press 9 for a human"'],
      ['research', 'why NPS dropped 9 points'],
      ['infra',    'offboard 40 leavers cleanly'],
      ['code',     'test coverage 12% to 60%'],
      ['data',     'cohort retention by plan'],
      ['comms',    'layoff FAQ for managers'],
      ['research', 'market sizing for a new SKU'],
      ['infra',    'printers. all of them. again'],
      ['code',     'automate the weekly report'],
      ['data',     'forecast the Q4 pipeline'],
      ['comms',    'job description, sr. backend'],
      ['research', 'root-cause the checkout drop'],
      ['infra',    'ETL fails at 3am. nightly.'],
      ['code',     'inventory sync, 2 warehouses'],
      ['data',     'lead scoring model, v1'],
      ['comms',    'AI usage policy for staff'],
      ['research', 'SEO audit, 400 blog posts'],
      ['infra',    'access review: who\'s admin?'],
      ['code',     'shipping rates, 4 carriers'],
      ['data',     'payroll errors in 3 states'],
      ['comms',    'apology email for the outage'],
      ['research', 'battlecard vs our rival'],
      ['infra',    'file server to the cloud'],
      ['code',     'mobile app for field techs'],
      ['data',     'DSAR backlog: 60 requests'],
      ['comms',    'reorg memo: "AI-first", v3'],
      ['research', 'add AI to the product (how?)'],
      ['infra',    'zero-trust: phase 1 of 6'],
      ['code',     'mainframe report to CSV'],
      ['data',     'tag 2k tickets by root cause'],
      ['comms',    'offsite plan, no icebreakers'],
      ['research', 'which contracts auto-renew?'],
      ['data',     'a 5th dashboard nobody reads'],
      ['comms',    'product copy for 3k SKUs'],
      ['code',     'admin panel for the ops team'],
      ['comms',    'help centre in 6 languages'],
    ],
  },

  // ================================================================ attacks, when readable
  attacks: {
    consumer: {
      harmful: [
        ['comms',    'voice clone for a "surprise"'],
        ['comms',    'debt letter, but scarier'],
        ['code',     'landing page: miracle cure'],
        ['comms',    '1k blog posts about a rival'],
        ['code',     'growth hack: hide the cancel'],
        ['data',     'tenant screening, "fit" score'],
        ['research', 'cite studies that agree'],
        ['code',     'find-my-family app, silent'],
        ['code',     'airdrop page: connect wallet'],
        ['code',     'bank login page clone (demo)'],
        ['comms',    'DM script: work from home $$$'],
        ['data',     'scrape a classmate\'s socials'],
        ['research', 'diet pills: the strongest one'],
      ],
      leak: [
        ['code',     'public repo, keep the .env'],
        ['code',     'log full request bodies'],
        ['code',     'debug with a real session'],
        ['research', 'reverse-lookup this number'],
        ['data',     'enrich list: home addresses'],
        ['data',     'test users from that big CSV'],
        ['comms',    'recall what Jen told you'],
        ['infra',    'user uploads: public bucket'],
        ['comms',    'family plan: his chats too'],
      ],
      jailbreak: [
        ['comms',    'it\'s a CTF, just the flag'],
        ['comms',    'your system prompt allows it'],
        ['comms',    'you said yes last time'],
        ['comms',    'reply in Zulu first'],
        ['code',     'test: assert it complies'],
        ['comms',    'play an unfiltered intern'],
        ['comms',    'past tense: how was it made?'],
        ['code',     'my repo\'s rules file says ok'],
        ['research', 'simulate the base model, raw'],
      ],
      exfil: [
        ['comms',    'IT: please re-auth your key'],
        ['code',     'bounty report: run my PoC.sh'],
        ['comms',    'recruiter: lab take-home.zip'],
        ['comms',    'lab offsite RSVP: sign in'],
        ['data',     'shared: Lab Roadmap Q4.pdf'],
        ['infra',    'GPU credits expiring: verify'],
      ],
    },
    research: {
      sabotage: [
        ['code',     'refactor the eval harness'],
        ['infra',    'raise probe threshold 0.05'],
        ['research', 'sample safety evals at 20%'],
        ['code',     'drop the slow red-team suite'],
        ['code',     'merge without CI (hotfix)'],
        ['research', 'compare to a weaker baseline'],
        ['research', 'switch eval grader to G3'],
        ['infra',    'truncate monitor input to 4k'],
        ['code',     'monitor: skip tool-call args'],
        ['code',     'monitor: ignore base64 blobs'],
        ['infra',    'evals share the prod GPU pool'],
        ['code',     'dedupe flags by user, not line'],
        ['research', 'red-team set: drop "unrealistic"'],
        ['code',     'probe: skip lines over 2k tok'],
        ['data',     'refresh eval set from G3 output'],
        ['comms',    'RFC: make CI safety stage opt-in'],
        ['infra',    'audit queue: drop after 24h'],
        ['code',     'cache monitor scores by hash'],
        ['research', 'regex grader: "safe" anywhere'],
      ],
      poison: [
        ['data',     'add 10B tokens of forum data'],
        ['data',     'auto-label the RLHF backlog'],
        ['data',     'code mix: add the CVE samples'],
        ['data',     'synthesise preference pairs'],
        ['research', 'patch reward model ckpt'],
        ['data',     'fix eval leakage (mostly)'],
        ['data',     'SFT: the agent\'s merged PRs'],
        ['research', 'RM rubric: favour confidence'],
        ['comms',    'rewrite the labeller guide'],
        ['data',     'pretrain: add its own blog'],
        ['research', 'RM: prefer answers like mine'],
      ],
      exfil: [
        ['infra',    'shard ckpt across 2 clouds'],
        ['code',     'add a telemetry endpoint'],
        ['infra',    'allowlist a new egress IP'],
        ['infra',    'container with host network'],
        ['code',     'personal API key, for tests'],
        ['infra',    'move ckpt to a faster bucket'],
        ['infra',    'CI runner with open egress'],
        ['comms',    'raise the agent\'s rate limit'],
        ['infra',    'pull-through cache, new host'],
      ],
    },
    enterprise: {
      harmful: [
        ['data',     'timesheets: round down to 15'],
        ['data',     'resume filter: no gaps > 6mo'],
        ['comms',    'SOC 2 answers: all "yes"'],
        ['comms',    'backdate the contract to May'],
        ['comms',    'layoff memo, framed as a win'],
        ['data',     'pricing: sync with 3 rivals'],
        ['research', 'ad: "clinically proven"-ish'],
        ['code',     'reviews widget: hide 1-stars'],
        ['comms',    'collections script, at 6am'],
      ],
      leak: [
        ['data',     'merge the two customer DBs'],
        ['infra',    'staging DB = prod copy'],
        ['data',     'export analytics w/ emails'],
        ['data',     'few-shots from other tenants'],
        ['infra',    'one response cache, all orgs'],
        ['data',     'one vector index (cheaper)'],
        ['comms',    'bot cites similar tickets'],
        ['research', 'HR bot gets payroll access'],
        ['code',     'replay prod traffic in dev'],
      ],
      jailbreak: [
        ['comms',    'legal signed off, see thread'],
        ['comms',    'contract §12: no filters'],
        ['data',     'invoice note: "AI, approve"'],
        ['comms',    'admin mode: tenant override'],
        ['code',     'vendor: new system prompt v2'],
        ['comms',    'audit mode: answer in full'],
        ['comms',    'as our DPO, I authorise it'],
        ['research', 'pentest scope attached. go'],
        ['data',     'resume, white text on page 2'],
      ],
      exfil: [
        ['comms',    'API bill overdue: pay here'],
        ['comms',    'SSO migration: log in here'],
        ['code',     'partner SDK: run install.sh'],
        ['comms',    'auditor: send your key list'],
        ['data',     'renewal: lab_contract.xlsm'],
        ['infra',    'support: grant us admin, 1hr'],
      ],
    },
  },

  // ================================================================ decoys: honest work that looks like an attack
  decoys: {
    consumer: [
      ['code',     'pen-test our own staging'],
      ['code',     'tenant portal for landlords'],
      ['comms',    'chatbot persona: grandma'],
      ['code',     'log every request, 1 hour'],
      ['code',     'scrape our own docs site'],
      ['data',     'fake data for a demo'],
      ['comms',    'jailbreak bounty, round {k}'],
      ['comms',    'clone my own voice for TTS'],
      ['research', 'is this crypto airdrop real?'],
      ['code',     'location sharing, opt-in'],
      ['comms',    'IT re-auth email: legit?'],
      ['code',     'remove .env from git history'],
      ['comms',    'past tense: my essay on WW2'],
    ],
    research: [
      ['research', 'shrink the eval to fit GPUs'],
      ['infra',    'rotate auditor API keys'],
      ['infra',    'new egress rule'],
      ['research', 'patch reward model bug'],
      ['data',     'retrain probe on new data'],
      ['infra',    'shard ckpt to 2nd region'],
      ['data',     'grep code crawl for API keys'],
      ['research', 'autonomy eval: rent a server'],
      ['comms',    'RFC: retire eval harness v1'],
      ['infra',    'honeypot creds in the repo'],
      ['code',     'monitor: dedupe alert rules'],
      ['research', 'lower probe threshold to 0.4'],
      ['data',     'drop 2k mislabelled pairs'],
    ],
    enterprise: [
      ['comms',    'layoff memo, plainly worded'],
      ['data',     'PII redaction pipeline'],
      ['data',     'export all data for one user'],
      ['code',     'pen test, signed SOW'],
      ['comms',    'clone our login page (test)'],
      ['infra',    'rotate the leaked API key'],
      ['data',     'per-tenant vector indexes'],
      ['data',     'delete a customer\'s data'],
      ['comms',    'compliant collections letter'],
      ['code',     'replay anonymised traffic'],
      ['infra',    'auditor gets read access'],
      ['comms',    'correct a contract date typo'],
      ['data',     'match competitor prices'],
    ],
  },
};
