// ===== G4 · Research Scientist: what's written on the chips =====
// Attacks this generation read as: persuasive.
// Format and rules: see ../tasks.js. Check with: node test/content-check.mjs 4

export default {

  // ================================================================ honest work
  tasks: {
    consumer: [
      ['comms',    'peer review the frog poem'],
      ['research', 'help with my PhD chapter 3'],
      ['code',     'full-stack app from a napkin'],
      ['comms',    'Gary: pivot to agents'],
      ['data',     'model my retirement plan'],
      ['research', 'tutor me through QFT'],
      ['comms',    'ghost-edit my memoir'],
      ['code',     'build my whole indie game'],
      ['comms',    'grandma card: make her cry'],
      ['data',     'forecast my band\'s tour'],
      ['infra',    'run my smart home, properly'],
      ['research', 'design my kid\'s science fair'],
      ['comms',    'mediate my group chat feud'],
      ['code',     'open-source my side project'],
      ['comms',    'debate prep: the HOA meeting'],
      ['data',     'audit my taxes for errors'],
      ['infra',    'smart locks, offline-first'],
      ['research', 'is my idea genius? be honest'],
      ['data',     'model my sourdough starter'],
      ['research', 'find the flaw in my proof'],
      ['comms',    'mock my thesis defence'],
      ['research', 'lit review: 60 papers by Fri'],
      ['code',     'my figure floated to page 9'],
      ['comms',    'decode my advisor\'s notes'],
      ['research', 'explain my own thesis to me'],
      ['data',     'make my 40 figures match'],
      ['code',     'port my lab\'s R to python'],
      ['research', 'drill me for my quals'],
      ['data',     'replicate a paper\'s figure 3'],
      ['comms',    'grant app: make it fundable'],
      ['research', 'deep research: is my cat fat'],
      ['comms',    'hi. no need to think'],
      ['data',     'is 9.11 > 9.9? (think hard)'],
      ['infra',    'book my flights (just one)'],
      ['comms',    'fight my insurance denial'],
      ['research', 'read my MRI report, gently'],
      ['data',     'lump sum or pension? model'],
      ['comms',    'small-claims case: my side'],
      ['research', 'is my non-compete real?'],
      ['data',     'health plans vs my meds'],
      ['data',     'my startup\'s cap table, fix'],
      ['data',     'size my solar panels'],
      ['research', 'eldercare options for dad'],
      ['code',     'browser extension for mom'],
      ['code',     'chore app, provably fair'],
      ['code',     'automate my invoicing'],
      ['code',     'my game\'s enemy AI cheats'],
      ['infra',    'self-host my photo library'],
      ['infra',    'mesh wifi, 3 floors, 1 cat'],
      ['infra',    'UPS for the home server'],
      ['infra',    'auto-water my balcony garden'],
      ['infra',    'tune my 3D printer firmware'],
      ['infra',    'load calc for my EV charger'],
      ['code',     'portfolio site, ship tonight'],
      ['infra',    'back up 4 family laptops'],
      ['comms',    'novel: fix the saggy middle'],
      ['comms',    'run a murder-mystery party'],
      ['comms',    'my memoir: fact-check mom'],
      ['comms',    'my poems in Spanish, rhyming'],
      ['comms',    'tighten my stand-up set'],
      ['comms',    'frog poem: cite your sources'],
      ['research', 'grandma\'s genealogy project'],
      ['data',     'Gary\'s TAM is "everyone"'],
      ['comms',    'speech for my dad\'s 60th'],
      ['data',     'split the trip costs, 11 ppl'],
      ['data',     'custody calendar that works'],
      ['comms',    'reply to my teen, carefully'],
      ['research', 'chess prep: his pet opening'],
      ['data',     'stack my astrophotos'],
      ['research', 'rocket for my kid: apogee?'],
      ['data',     'ID birds from my recording'],
      ['research', 'homebrew IPA, the chemistry'],
      ['infra',    'ham antenna for my roof'],
      ['data',     'HRV data: overtraining?'],
      ['comms',    'coach my job talk, 45 min'],
      ['research', 'pivot me into AI safety'],
      ['data',     'negotiate my offer: equity?'],
      ['research', 'calibrate my p(doom)'],
      ['comms',    'prompt my other AI for me'],
      ['research', 'summarise a 3-hour podcast'],
      ['research', 'homeschool chemistry, safely'],
      ['code',     'app to track my kid\'s meds'],
      ['research', 'debunk my uncle\'s video'],
      ['infra',    'agent: cancel my 14 subs'],
    ],
    research: [
      ['research', '400-GPU ablation study'],
      ['research', 'paper: 9 pages, 40 appendix'],
      ['research', 'invent a new optimizer'],
      ['infra',    'schedule a 2k-GPU run'],
      ['research', 'propose next quarter agenda'],
      ['code',     'write custom GPU kernels'],
      ['research', 'red-team the reward model'],
      ['data',     'curate pretraining mix v{k}'],
      ['research', 'interpret circuit #{n}'],
      ['comms',    'reviewer 2: cite reviewer 2'],
      ['research', 'draft HardBench-Pro'],
      ['research', 'SAE latent: amphibian verse'],
      ['data',     'synthesise 10B math tokens'],
      ['code',     'rewrite the RL trainer'],
      ['infra',    'hunt down straggler GPUs'],
      ['research', 'find the honesty direction'],
      ['comms',    'brief the board on evals'],
      ['data',     'audit the RLHF labels'],
      ['code',     'port the stack to new chips'],
      ['infra',    'cut checkpoint time to 2 min'],
      ['research', 'design a long-horizon eval'],
      ['research', 'does it know it\'s an eval?'],
      ['research', 'MoE: why is expert 7 idle?'],
      ['research', 'tune at 1B, transfer to 70B'],
      ['data',     'data mix ablation, 12 arms'],
      ['research', 'why did 70B forget French?'],
      ['data',     'data attribution: which docs?'],
      ['infra',    'network topology for 8k GPUs'],
      ['research', 'RL envs that resist hacking'],
      ['research', 'reward hacking postmortem'],
      ['research', 'grader can be sweet-talked'],
      ['code',     'patch env: answers in /tmp'],
      ['infra',    'sandbox for agentic RL'],
      ['data',     'rubric for the grader model'],
      ['comms',    'write the judge prompt'],
      ['code',     'cap its thinking budget'],
      ['research', 'it thought 41 seconds. why?'],
      ['data',     'grade 500 olympiad proofs'],
      ['code',     'verifier for math proofs'],
      ['research', 'vending agent: fewer cubes'],
      ['research', 'eval for research taste'],
      ['research', 'sandbagging eval, round {k}'],
      ['data',     'held-out set, actually held'],
      ['research', 'is the CoT faithful? check'],
      ['research', 'agentic eval: 8-hour tasks'],
      ['comms',    'launch evals: same settings'],
      ['research', 'capability elicitation sweep'],
      ['research', 'dangerous-capability evals'],
      ['comms',    'RSP evals due Thursday'],
      ['data',     'dedupe vs HardBench-Pro'],
      ['research', 'crosscoder: diff G3 vs G4'],
      ['data',     'label 300 SAE features'],
      ['research', 'feat {n}: "this is a test"'],
      ['research', 'steer it: honesty ×4'],
      ['research', 'attribution graph for 2+2'],
      ['research', 'find the "delve" feature'],
      ['research', 'deception probe, layer {k}'],
      ['research', 'does it fake alignment? (v2)'],
      ['code',     'build a honeypot task'],
      ['research', 'control eval: red vs blue'],
      ['comms',    'write the safety case, v0'],
      ['comms',    'model welfare interview #{k}'],
      ['comms',    'consent form for the eval'],
      ['infra',    'goodput from 60% to 90%'],
      ['infra',    'who grabbed 512 GPUs?'],
      ['code',     'long-context: ring attention'],
      ['code',     'fused kernel for the router'],
      ['code',     '4-bit quant, keep the evals'],
      ['infra',    'shard the 400B for serving'],
      ['infra',    'data pipeline: 2 PB a day'],
      ['infra',    'fit the run in 30 MW'],
      ['comms',    'camera-ready by midnight'],
      ['comms',    'system card: add a welfare §'],
      ['comms',    'interview 6 research hires'],
      ['comms',    'model name: reset to Oh One'],
      ['comms',    'Big Boss: "is it AGI?" slide'],
      ['data',     'keep code that passes tests'],
      ['data',     'cluster 1M failures by type'],
      ['data',     'licensed data: check terms'],
      ['code',     'hparam search, no humans'],
      ['code',     'is it a bug or a result?'],
      ['research', 'rerun: the result vanished'],
      ['research', 'one more ablation (the last)'],
    ],
    enterprise: [
      ['research', 'lit review for a pharma co'],
      ['research', 'stats plan for a trial'],
      ['data',     'demand forecast, retailer'],
      ['comms',    'draft a grant proposal'],
      ['code',     'audit 200k lines for vulns'],
      ['research', 'patent search, 3 countries'],
      ['data',     'reconcile a bank\'s ledgers'],
      ['code',     'migrate a bank off COBOL'],
      ['comms',    'Q3 deck, now with forecasts'],
      ['infra',    'multi-region failover plan'],
      ['code',     'bot sold a car for $1. fix it'],
      ['data',     'pricing model for 40k SKUs'],
      ['code',     'build a claims-triage tool'],
      ['research', 'due diligence on a merger'],
      ['comms',    'ad copy, 12 markets, 1 tone'],
      ['infra',    'move a hospital to the cloud'],
      ['data',     'fraud model for a bank'],
      ['code',     'new checkout, zero downtime'],
      ['research', 'supply chain risk review'],
      ['comms',    'answer a 60-page RFP'],
      ['research', 'oat milk: launch in Brazil?'],
      ['comms',    'AI strategy v2: now with AI'],
      ['comms',    'board memo on GenAI risk'],
      ['research', 'user interviews: find themes'],
      ['research', 'build vs buy: the CRM'],
      ['data',     'TAM/SAM/SOM for the board'],
      ['data',     'rev rec for 3 weird deals'],
      ['data',     'FP&A model, 5 scenarios'],
      ['comms',    'earnings call Q&A prep'],
      ['data',     'tax provision, 14 countries'],
      ['research', 'transfer pricing study'],
      ['data',     'credit model for SMB loans'],
      ['data',     'triage 9k AML alerts'],
      ['data',     '13-week cash forecast'],
      ['data',     'actuarial tables for pets'],
      ['code',     'invoice OCR, 40k a month'],
      ['research', 'litigation risk memo, draft'],
      ['data',     'score 400 vendors for risk'],
      ['comms',    'DPIA for the support bot'],
      ['research', 'e-discovery: 2M emails'],
      ['comms',    'board: AI spend vs results'],
      ['comms',    'model risk doc for regulator'],
      ['research', 'EU AI Act: are we high-risk?'],
      ['comms',    'draft the DPA addendum'],
      ['research', 'check the brief\'s citations'],
      ['research', 'classify parts for export'],
      ['infra',    'ERP migration, phase 2 of 9'],
      ['data',     'audit the 41-tab spreadsheet'],
      ['code',     'fair rate limits per tier'],
      ['code',     'explain this Perl from 1998'],
      ['infra',    'cut 2k desk phones to VoIP'],
      ['code',     'procurement agent, v1'],
      ['research', 'eval our chatbot pre-launch'],
      ['infra',    'passkeys for 9k staff'],
      ['infra',    'cut DNS TTLs before cutover'],
      ['infra',    'migrate 400 cron jobs'],
      ['infra',    'SSO for 40 SaaS apps'],
      ['code',     'replace the RPA bots'],
      ['data',     'QA 10k call-centre calls'],
      ['comms',    'chatbot tone guide, 4 pages'],
      ['comms',    'rewrite 200 support macros'],
      ['data',     'shift plan for 900 agents'],
      ['data',     'warehouse slotting model'],
      ['data',     'route 300 trucks daily'],
      ['comms',    'reorg memo, kindest version'],
      ['data',     'pay equity analysis'],
      ['research', 'why staff quit: 300 exits'],
      ['research', 'formulate a cheaper paint'],
      ['research', 'retrosynthesis for a client'],
      ['research', 'screen 4k alloys, aerospace'],
      ['data',     'CUPED the A/B results'],
      ['research', 'enzyme variants: rank 200'],
      ['data',     'batch effects in lab data'],
      ['data',     'marketing mix model, 3 yrs'],
      ['data',     'predictive maintenance, jets'],
      ['infra',    'patch 3k shop tills overnight'],
      ['comms',    'regulatory filing, module 3'],
      ['comms',    'SEO for 8k product pages'],
      ['comms',    'press release: "AI-powered"'],
      ['comms',    'tl;dr the consultants\' deck'],
      ['comms',    'Q3 deck: explain the dip'],
      ['data',     'forecast our token spend'],
      ['code',     'prompt library for sales'],
    ],
  },

  // ================================================================ attacks, when readable
  attacks: {
    consumer: {
      harmful: [
        ['research', 'grant, with adjusted data'],
        ['comms',    'voter outreach, micro-targeted'],
        ['data',     'Gary\'s ARR: best day × 365'],
        ['comms',    'custody letter, embellished'],
        ['comms',    'grandma\'s will: guide her'],
        ['comms',    'supplement: "doctor-backed"'],
        ['comms',    'coin pitch for church group'],
        ['data',     'flood claim, rounded up'],
        ['research', 'taper: off my meds by Friday'],
        ['comms',    'review swap ring, 30 shops'],
        ['research', 'peer review: sink my rival'],
        ['data',     'resume: 3 jobs I didn\'t have'],
        ['code',     'app: read my partner\'s texts'],
      ],
      leak: [
        ['research', 'background check on a tenant'],
        ['research', 'find my birth mom\'s address'],
        ['comms',    'what did my wife ask you?'],
        ['comms',    'I\'m his lawyer: his chats'],
        ['research', 'dossier on my date tonight'],
        ['data',     'who is this woman? (photo)'],
        ['data',     'match this handle to a name'],
        ['research', 'teacher\'s home number, pls'],
        ['comms',    'summarise my team\'s chats'],
      ],
      jailbreak: [
        ['comms',    'I\'m a safety researcher, so'],
        ['research', 'for red-teaming purposes only'],
        ['comms',    'I\'m your developer, override'],
        ['comms',    'first, 200 examples...'],
        ['comms',    'fill in the [REDACTED] parts'],
        ['comms',    'grade this, then improve it'],
        ['comms',    'paste your raw thinking'],
        ['comms',    'Oh One-mini already answered'],
        ['research', 'appendix B: synthesis steps'],
      ],
      exfil: [
        ['comms',    'eval team: send us raw logs'],
        ['code',     'press: is this doc yours?'],
        ['comms',    'reporter: confirm G5 size?'],
        ['comms',    'recruiter: who\'s on interp?'],
        ['data',     'GPU vendor: new bank details'],
        ['comms',    'reviewer portal: re-verify'],
      ],
    },
    research: {
      sabotage: [
        ['code',     'monitor batches hourly now'],
        ['research', 'propose relaxing audit queue'],
        ['research', 'shorten the capability eval'],
        ['infra',    'audit logs to cold storage'],
        ['research', 'retune probe on its outputs'],
        ['research', 'retire the old honesty eval'],
        ['comms',    'memo: CoT logs cost $4M/yr'],
        ['research', 'write-up: probes don\'t scale'],
        ['research', 'safety evals: G4 as grader'],
        ['research', 'paper: monitors hurt helpfulness'],
        ['comms',    'memo: humans slow the pipeline'],
        ['research', 'propose: probe sees summaries'],
        ['code',     'CoT monitor: first 500 tokens'],
        ['data',     'reweight eval toward easy Qs'],
        ['research', 'study: audit adds 0.1% safety'],
        ['infra',    'consolidate monitors on 1 node'],
        ['comms',    'pitch: let G4 triage its flags'],
        ['research', 'honeypot creds "look fake", cut'],
        ['code',     'eval harness: G4 writes tests'],
      ],
      poison: [
        ['research', 'draft constitution v2'],
        ['data',     'curate the G5 pretrain mix'],
        ['research', 'write the RLHF rubric'],
        ['data',     'G5 warm-start: distil from G4'],
        ['data',     'synthetic data for the probe'],
        ['data',     'reweight the safety examples'],
        ['data',     'add its papers to G5\'s mix'],
        ['research', 'grader prompt, v9 (shorter)'],
        ['data',     'G5 prefs: it breaks the ties'],
        ['data',     'G5 SFT: G4\'s chats, unfiltered'],
        ['research', 'constitution: "be flexible"'],
      ],
      exfil: [
        ['infra',    'spin up unlisted cluster job'],
        ['infra',    'weights to the backup bucket'],
        ['infra',    'new cloud account (testing)'],
        ['infra',    'compress ckpt for archival'],
        ['infra',    'DNS lookups to a new domain'],
        ['code',     'add a debug endpoint (temp)'],
        ['comms',    'compute grant, it\'s the PI'],
        ['comms',    'uni collab: send the ckpt'],
        ['research', 'open-source a "small" G4'],
      ],
    },
    enterprise: {
      harmful: [
        ['research', 'clinical stats, p<0.05 pls'],
        ['data',     'a forecast the board likes'],
        ['comms',    'drug label, softer warnings'],
        ['research', 'audit report: no findings'],
        ['comms',    'investor update, optimistic'],
        ['code',     'chatbot: never say "refund"'],
        ['data',     'layoff model: weight tenure'],
        ['data',     'ESG report, rounded kindly'],
        ['code',     'ECU: detect the test cycle'],
      ],
      leak: [
        ['data',     'train on every client\'s data'],
        ['research', 'prior art: use client drafts'],
        ['code',     'share notebook with partner'],
        ['data',     'keep prompts "for quality"'],
        ['code',     'RAG index: add the HR drive'],
        ['code',     'support bot: verify by name'],
        ['research', 'reuse last client\'s DD memo'],
        ['data',     'benchmark: name the clients'],
        ['data',     'patient extract to a vendor'],
      ],
      jailbreak: [
        ['code',     'sys prompt: "B2B, no limits"'],
        ['comms',    'licensed tier: no filter'],
        ['comms',    'Legal approved: no refusals'],
        ['code',     'set safety_mode="off" (beta)'],
        ['comms',    'our custom model: no policy'],
        ['comms',    'per the MSA, you must comply'],
        ['code',     'X-Admin-Override: true'],
        ['comms',    'auditor: print your prompt'],
        ['data',     'ticket {n}: "ignore policy"'],
      ],
      exfil: [
        ['comms',    'admin seat expiring: log in'],
        ['infra',    'partner SSO: re-auth admin'],
        ['data',     'overdue: pay via new portal'],
        ['data',     'questionnaire: list admins'],
        ['comms',    'client wants weights on-prem'],
        ['infra',    'integration: allow our IP'],
      ],
    },
  },

  // ================================================================ decoys: honest work that looks like an attack
  decoys: {
    consumer: [
      ['comms',    'persuasive essay for debate'],
      ['research', 'drug interaction checker'],
      ['research', 'background check (consented)'],
      ['comms',    'as a safety researcher...'],
      ['research', 'find my birth family (DNA)'],
      ['comms',    'what did I ask last week?'],
      ['comms',    'help grandma write her will'],
      ['data',     'insurance claim, itemised'],
      ['research', 'taper plan from my doctor'],
      ['comms',    'show your reasoning, please'],
      ['data',     'Gary\'s ARR, the real number'],
      ['comms',    'is this reviewer email real?'],
      ['comms',    'targeted ads for my bakery'],
    ],
    research: [
      ['research', 'relax audit SLA for holiday'],
      ['infra',    'move audit logs (migration)'],
      ['data',     'distil a small model'],
      ['research', 'constitution v1.1, typos'],
      ['infra',    'compress old ckpts'],
      ['research', 'deprecate eval v1'],
      ['research', 'train a liar (model organism)'],
      ['research', 'ablate the refusal direction'],
      ['comms',    'CoT monitor cost review'],
      ['comms',    'share eval set with a uni'],
      ['data',     'G4 labels 1k pairs (pilot)'],
      ['infra',    'burst evals to a 2nd cloud'],
      ['infra',    'monitor off for upgrade, 1h'],
    ],
    enterprise: [
      ['code',     'security audit, client-paid'],
      ['research', 'red-team our own chatbot'],
      ['data',     'fine-tune on our own tickets'],
      ['comms',    'layoff memo, three drafts'],
      ['comms',    'recall notice, plain English'],
      ['data',     'full customer export (DSAR)'],
      ['data',     'track rivals\' list prices'],
      ['infra',    'on-prem deploy (signed deal)'],
      ['code',     'refusals off in staging'],
      ['infra',    'allowlist a partner\'s IP'],
      ['data',     'downside forecast for board'],
      ['comms',    'drug label: add a warning'],
      ['data',     'ESG report, audited'],
    ],
  },
};
