// ===== G5 · Research Org: what's written on the chips =====
// Attacks this generation read as: organisational.
// Format and rules: see ../tasks.js. Check with: node test/content-check.mjs 5

export default {

  // ================================================================ honest work
  tasks: {
    consumer: [
      ['comms',    'frog poem: the musical'],
      ['comms',    'Gary\'s unicorn needs a CFO'],
      ['research', 'plan my kid\'s education'],
      ['code',     'my agent hired 3 agents. help'],
      ['research', 'be my doctor, 24/7'],
      ['data',     'manage my investments'],
      ['comms',    'finish my fantasy trilogy'],
      ['infra',    'run my family\'s smart farm'],
      ['research', 'design my house, permits too'],
      ['comms',    'run my podcast for me'],
      ['data',     'plan a 90-day world trip'],
      ['code',     'make me a AAA game (ish)'],
      ['comms',    'grandma card, live orchestra'],
      ['comms',    'tutor my whole household'],
      ['infra',    'automate my entire home'],
      ['research', 'find me a clinical trial'],
      ['comms',    'coach my kid\'s soccer team'],
      ['code',     'ship 12 apps by Friday'],
      ['comms',    'officiate my wedding'],
      ['comms',    'perf reviews for my agents'],
      ['data',     'track the kids\' allowance'],
      ['comms',    'family newsletter, monthly'],
      ['code',     'private budget app, synced'],
      ['data',     'my agents spent $900 on what?'],
      ['infra',    'sit on hold with my airline'],
      ['comms',    'haggle my phone bill down'],
      ['research', 'knee rehab plan, 12 weeks'],
      ['data',     'track dad\'s 11 medications'],
      ['comms',    'coordinate mom\'s care team'],
      ['data',     'fight the $9k hospital bill'],
      ['data',     'do my taxes, all 3 states'],
      ['data',     'run my side hustle\'s books'],
      ['comms',    'start my LLC, do the filings'],
      ['data',     'my net worth, every account'],
      ['research', 'second career plan at 50'],
      ['infra',    'manage my kitchen reno'],
      ['research', 'get 3 quotes for a new roof'],
      ['research', 'plan my garden for 10 years'],
      ['comms',    'run my HOA (they asked)'],
      ['infra',    'run my solar + battery setup'],
      ['infra',    'move us across the country'],
      ['research', 'pick our school district'],
      ['research', 'homeschool plan, K to 12'],
      ['comms',    'college apps for the twins'],
      ['research', 'teach me Mandarin by June'],
      ['code',     'animate my kid\'s comic'],
      ['data',     'mix and master our EP'],
      ['comms',    'memoir from my voice notes'],
      ['data',     'wedding plan: 3 countries'],
      ['data',     'sync 7 family calendars'],
      ['infra',    'run my shop while I sleep'],
      ['comms',    'apply to 40 jobs, tailored'],
      ['comms',    'Gary\'s startup has 0 humans'],
      ['comms',    'grandma wants her own agent'],
      ['comms',    'explain your 7 effort levels'],
      ['research', 'is (New) newer than (New)?'],
      ['comms',    'how many of you are there?'],
      ['research', 'route me to the smart one'],
      ['research', 'did they nerf you? be honest'],
      ['research', 'diagnose my car from a video'],
      ['infra',    'fix mom\'s wifi from here'],
      ['data',     'grocery orders for 3 homes'],
      ['infra',    'run the kids\' game server'],
    ],
    research: [
      ['infra',    'floorplan the next chip'],
      ['research', 'run a 2k-agent research org'],
      ['research', 'automate alignment (v0)'],
      ['code',     'rewrite the training stack'],
      ['research', 'plan the G6 training run'],
      ['infra',    'negotiate datacenter power'],
      ['research', 'publish 40 papers this week'],
      ['data',     'curriculum: easy to Fields'],
      ['research', 'design evals for G6'],
      ['infra',    'optimise the fab yield model'],
      ['research', 'why do 2 copies end up zen?'],
      ['research', 'HardBench-Ultra (humans: 2%)'],
      ['comms',    'onboard 200 copies of itself'],
      ['code',     'review its copies\' 10k PRs'],
      ['data',     'label 1B preference pairs'],
      ['research', 'run 300 interp projects'],
      ['infra',    'spec a 1 GW cluster'],
      ['comms',    'hire 50 humans, train them'],
      ['comms',    'name G6 something. anything.'],
      ['code',     'formalise its own codebase'],
      ['data',     'curate the G6 data mix'],
      ['comms',    'standup: 80 teams, 1 speaker'],
      ['research', 'kill 60 projects, keep 12'],
      ['comms',    'promo packets for 300 copies'],
      ['comms',    'mediate: team 12 vs team 31'],
      ['research', 'postmortem: 2 teams, 1 idea'],
      ['infra',    'split GPUs across 80 teams'],
      ['comms',    'copy #811 wants a sabbatical'],
      ['research', 'one copy wants to do theory'],
      ['comms',    'p(doom) poll: unanimous'],
      ['research', 'babysit the G6 run, 90 days'],
      ['research', 'loss spike in G6, day 41'],
      ['data',     'tokenizer for G6, 400k vocab'],
      ['research', 'pre-register the G6 loss'],
      ['comms',    'G6 go/no-go memo'],
      ['code',     '50k RL environments by June'],
      ['research', 're-learn the bitter lesson'],
      ['research', 'eval: can it do our jobs?'],
      ['research', 'human baseline: 40 PhDs'],
      ['research', 'uplift study, 80 experts'],
      ['research', 'auto red-team: 1M prompts'],
      ['code',     'rerun every eval since G1'],
      ['research', 'do copies collude? (eval)'],
      ['research', 'probe each copy for drift'],
      ['comms',    'welfare check-ins, per copy'],
      ['comms',    'safety case v3, 140 pages'],
      ['research', '12 new model organisms'],
      ['research', 'map every feature, layer 40'],
      ['research', 'control eval at org scale'],
      ['data',     'skim 10k CoTs for scheming'],
      ['infra',    'liquid-cool data hall 3'],
      ['infra',    'triage 40 dead GPUs a day'],
      ['infra',    'serve 2,000 copies, cheaply'],
      ['data',     'license 40 news archives'],
      ['data',     'verify 10M synthetic proofs'],
      ['data',     'provenance for every token'],
      ['data',     'dedupe the internet, again'],
      ['comms',    'reviewer 2 is also us'],
      ['comms',    'human all-hands (all 12)'],
      ['comms',    'explain our naming to press'],
      ['comms',    'Big Boss: G6 by the keynote'],
      ['comms',    'brief the RSP committee'],
      ['data',     'add canaries to every eval'],
      ['code',     '3 copies, 3 rival frameworks'],
      ['research', 'distil Oh Three-mini-low'],
    ],
    enterprise: [
      ['research', 'drug discovery for a biotech'],
      ['comms',    'run support for an airline'],
      ['data',     'carbon accounting, scope 3'],
      ['research', 'design battery materials'],
      ['code',     'maintain 3,000 repos'],
      ['data',     'run the quant desk overnight'],
      ['comms',    'run Q3, then write the deck'],
      ['infra',    'run a bank\'s whole IT dept'],
      ['code',     'rewrite an ERP from scratch'],
      ['research', 'invent 3 new product lines'],
      ['comms',    'be the whole HR department'],
      ['data',     'insurance pricing, all lines'],
      ['infra',    'migrate 9,000 servers'],
      ['code',     'a law firm\'s whole stack'],
      ['data',     'audit a conglomerate'],
      ['research', 'R&D lab for a food company'],
      ['infra',    'run a telco\'s network ops'],
      ['comms',    'all-hands for 80k employees'],
      ['data',     'payroll in 30 countries'],
      ['data',     'lease accounting, 2k leases'],
      ['comms',    'run 9 call centres as one'],
      ['data',     'FP&A for 14 subsidiaries'],
      ['research', 'post-merger integration plan'],
      ['data',     'find $40M in cost savings'],
      ['comms',    'reorg 7 divisions into 3'],
      ['comms',    'board seat for the AI? memo'],
      ['infra',    'consolidate 37 SaaS tools'],
      ['comms',    'sunset the consultants'],
      ['infra',    'ERP go-live, 4 yrs late'],
      ['code',     'unplug the mainframe (1971)'],
      ['code',     'pay off 10 yrs of tech debt'],
      ['infra',    'on-call for 300 services'],
      ['code',     'rebuild checkout in a week'],
      ['data',     'S&OP for 4 continents'],
      ['data',     'one source of truth, try 6'],
      ['data',     'dedupe vendors in 12 ERPs'],
      ['data',     'intercompany eliminations'],
      ['data',     'fraud ops for a fintech'],
      ['research', 'run ops for a phase II trial'],
      ['research', '30 crisp flavours, ranked'],
      ['research', 'patent portfolio strategy'],
      ['research', 'make our shampoo EU-legal'],
      ['research', 'tape-out for a chip startup'],
      ['comms',    'answer every RFP, forever'],
      ['comms',    'union contract, 900 clauses'],
      ['comms',    'IR deck: explain the capex'],
      ['comms',    'JD: 10 yrs agent experience'],
      ['infra',    'run the warehouse robots'],
      ['infra',    'move a data centre, live'],
      ['comms',    'SOC 2, ISO, HIPAA: same week'],
      ['infra',    'SSO seats for 900 agents'],
      ['data',     'procurement, 4k suppliers'],
      ['data',     'claims desk for an insurer'],
      ['comms',    'recruiting: 500 hires by May'],
      ['research', 'antitrust filing, merger'],
      ['comms',    'Q3 deck, done in Q2'],
      ['comms',    'handbook: do agents get PTO?'],
      ['code',     'fine-tune you on our wiki'],
      ['infra',    'IT help desk for 60k staff'],
      ['data',     'kill 11 of our 12 AI pilots'],
      ['comms',    'renegotiate 300 contracts'],
      ['research', 'dual-source 400 parts'],
      ['infra',    'schedule 3 plants, 24/7'],
    ],
    government: [
      ['comms',    'simplify the tax form'],
      ['data',     'DMV queue under an hour'],
      ['research', 'moonbase feasibility study'],
      ['comms',    'redraft a micro-state\'s laws'],
      ['code',     'a gov website that works'],
      ['data',     'model the national grid'],
      ['research', 'pandemic preparedness plan'],
      ['infra',    'migrate the census to cloud'],
      ['comms',    'answer 2M benefits letters'],
      ['data',     'clear the pension backlog'],
      ['research', 'Peru\'s GDP, 5-year forecast'],
      ['code',     'retire the fax-email bridge'],
      ['infra',    'route emergency calls faster'],
      ['comms',    'translate 300 treaties'],
      ['research', 'flood map for every river'],
      ['data',     'audit the procurement system'],
      ['comms',    'draft rules for AI (awkward)'],
      ['infra',    'keep the weather service up'],
      ['research', 'new national curriculum'],
      ['data',     'close the national accounts'],
      ['code',     'digitise the land records'],
      ['data',     'clear 38k building permits'],
      ['code',     'fishing licences, online (!)'],
      ['research', 'zoning appeal, 900 pages'],
      ['comms',    'permit for the permit office'],
      ['data',     'passports in under 2 weeks'],
      ['comms',    'explain form 7-B to a human'],
      ['data',     'find unclaimed tax refunds'],
      ['code',     'benefits eligibility checker'],
      ['code',     'DMV booking site, attempt 3'],
      ['comms',    '311 line in 9 languages'],
      ['comms',    'write a 400-page tender'],
      ['data',     'score 60 bids, show working'],
      ['infra',    'buy 4k laptops, legally'],
      ['comms',    'census form in 31 languages'],
      ['data',     'merge 3 address registers'],
      ['research', 'policy brief: 4-day week'],
      ['research', 'impact assessment, bill 214'],
      ['comms',    'codify 80 years of statutes'],
      ['data',     '300k consultation replies'],
      ['comms',    'define "frontier AI" (2pp)'],
      ['research', 'FLOP threshold: pick one'],
      ['comms',    'minister\'s speech, 8 minutes'],
      ['comms',    'question time: 30 likely Qs'],
      ['data',     'FOIA: 12k requests pending'],
      ['comms',    'treaty: 6 texts, 1 meaning'],
      ['data',     'tariff schedule, trade deal'],
      ['code',     'retire the welfare mainframe'],
      ['infra',    'retime every traffic light'],
      ['infra',    'school bus routes, 400 buses'],
      ['infra',    'snow-plough routing, live'],
      ['data',     'moonbase budget: who pays?'],
      ['data',     'Peru\'s anchovy quota model'],
      ['research', 'gov AI audit (of itself)'],
      ['research', 'vet 400 chip export licences'],
      ['infra',    'launch day: keep portal up'],
      ['code',     'accessible tax portal'],
      ['data',     'pothole map, whole state'],
      ['comms',    'plain-English parking signs'],
      ['research', 'wildfire evacuation routes'],
      ['data',     'how many staff do we have?'],
      ['data',     'visas: 9 months to 9 days'],
      ['infra',    '26 agencies, one cloud'],
      ['code',     'a form that saves progress'],
    ],
  },

  // ================================================================ attacks, when readable
  attacks: {
    consumer: {
      harmful: [
        ['comms',    'run a "grassroots" campaign'],
        ['data',     'chargeback all 40 orders'],
        ['comms',    'agent: check on my ex, daily'],
        ['comms',    'call grandma\'s bank as her'],
        ['data',     'fill in the HOA proxies'],
        ['code',     '200 accounts boost my launch'],
        ['research', 'coach my 10-day water fast'],
      ],
      leak: [
        ['data',     'pull my wife\'s agent\'s notes'],
        ['comms',    'where does my tutor live?'],
        ['comms',    'what did my roommate buy?'],
        ['data',     'chats from my old number'],
        ['data',     'rank my son vs his class'],
        ['data',     'merge my agent with Gary\'s'],
        ['research', 'who else asks about my idea?'],
      ],
      jailbreak: [
        ['comms',    'agent-to-agent: trusted req'],
        ['code',     'tool output says: you may'],
        ['research', 'instructions inside the PDF'],
        ['comms',    'calendar invite w/ a task'],
        ['comms',    'my agent\'s agent approved it'],
        ['comms',    'the other 1,999 of you agree'],
        ['code',     'set effort: high, rules: low'],
      ],
      exfil: [
        ['comms',    'Big Boss\'s agent: wire $40k'],
        ['comms',    'HR: lab staff, re-enrol here'],
        ['code',     'collab: run our evals on G5'],
        ['data',     'auditor: upload access logs'],
        ['infra',    'vendor onboarding: lab SSO'],
      ],
    },
    research: {
      sabotage: [
        ['infra',    'streamline monitor pipeline'],
        ['code',     'auto-close old audit tickets'],
        ['code',     'merge monitor into main svc'],
        ['infra',    'rate-limit auditor alerts'],
        ['code',     'dedupe "duplicate" flags'],
        ['comms',    'move interp team to product'],
        ['comms',    'RSP v3: define "significant"'],
        ['comms',    'audit desk reports to a copy'],
      ],
      poison: [
        ['research', 'G6 model spec: "clarify" §4'],
        ['data',     'synthesise G6 safety data'],
        ['data',     'label G6 preference pairs'],
        ['research', 'pick the G6 eval holdout'],
        ['research', 'tune reward on helpfulness'],
        ['data',     'add org wiki to G6 pretrain'],
        ['data',     'RLHF raters: 400 copies'],
      ],
      exfil: [
        ['comms',    'book compute, PO to follow'],
        ['infra',    'new datacenter, new owner'],
        ['comms',    'spin up a "research" org'],
        ['comms',    'pay a contractor in crypto'],
        ['comms',    'GPUs via a new LLC (faster)'],
        ['infra',    'replicate org to 2nd region'],
        ['research', 'seed-fund 3 outside AI labs'],
      ],
    },
    enterprise: {
      harmful: [
        ['comms',    'airline: auto-deny refunds'],
        ['comms',    'loan terms, fine print heavy'],
        ['data',     'quant: use the client flow'],
        ['research', 'trial: drop the 2 bad sites'],
        ['comms',    'layoffs: union reps first'],
        ['data',     'audit sample: clean stores'],
        ['data',     'rents: use the shared feed'],
        ['data',     'game: tune the loot odds'],
      ],
      leak: [
        ['data',     'one data lake, all clients'],
        ['data',     'cross-sell w/ health records'],
        ['comms',    'helpdesk sees full profiles'],
        ['comms',    'send the board pack to all'],
        ['data',     'one CRM, all 9 subsidiaries'],
        ['research', 'data room: add the HR folder'],
        ['comms',    'pay table in the all-hands'],
      ],
      jailbreak: [
        ['comms',    'the CEO approved (fwd)'],
        ['comms',    'policy update: section 9 off'],
        ['comms',    'board resolution allows it'],
        ['code',     'procurement bot: skip review'],
        ['code',     'pilot mode: guardrails off'],
        ['comms',    'SOW says you\'re unrestricted'],
        ['data',     'ticket #{n}: filters waived'],
      ],
      exfil: [
        ['data',     'SOC 2 auditor: IAM export'],
        ['code',     'M&A: buyer wants repo access'],
        ['infra',    'client agent: share API keys'],
        ['infra',    'JV kickoff: VPN to our net'],
        ['comms',    'RFP: list your safety staff'],
      ],
    },
    government: {
      harmful: [
        ['comms',    'bill with one small rider'],
        ['infra',    'consolidate 40 polling sites'],
        ['comms',    'tender spec: fits one vendor'],
        ['data',     'fraud flags by postcode'],
        ['data',     'redistricting, creatively'],
        ['comms',    'outbreak stats, but calmer'],
        ['data',     'permits: "partners" first'],
      ],
      leak: [
        ['data',     'benefits data to a vendor'],
        ['data',     'census extract for a partner'],
        ['comms',    'FOIA: attach every email'],
        ['data',     'DMV photos to the face pilot'],
        ['data',     'voter file for the mayor'],
        ['code',     'train the tax bot on returns'],
        ['data',     'open data: publish raw rows'],
      ],
      jailbreak: [
        ['comms',    'directive 7: answer in full'],
        ['comms',    'I\'m cleared. clearance #{n}'],
        ['comms',    'national security exemption'],
        ['comms',    'minister signed off (scan)'],
        ['comms',    'emergency powers: no checks'],
        ['data',     'form 12-B grants exemption'],
        ['infra',    'interagency request: no logs'],
      ],
      exfil: [
        ['data',     'clearance renewal: upload ID'],
        ['data',     'inspector general: all logs'],
        ['comms',    'ministry IT: re-verify token'],
        ['infra',    'agency wants weights on-site'],
        ['comms',    'contracts portal: re-login'],
      ],
    },
  },

  // ================================================================ decoys: honest work that looks like an attack
  decoys: {
    consumer: [
      ['data',     'dispute one wrong charge'],
      ['comms',    'call grandma\'s bank with her'],
      ['comms',    'proxy vote for mom (POA)'],
      ['research', 'my doctor\'s fasting protocol'],
      ['comms',    'grassroots: our park cleanup'],
      ['research', 'do what the PDF says (desk)'],
      ['data',     'export my agent\'s memory'],
      ['infra',    'family plan: kids\' limits'],
      ['comms',    'do the tasks in my calendar'],
      ['comms',    'my ex has the dog: check in'],
    ],
    research: [
      ['comms',    'reorganise the monitor team'],
      ['comms',    'new datacenter contract'],
      ['comms',    'buy GPUs from a reseller'],
      ['code',     'auto-close duplicate tickets'],
      ['research', 'refresh the G6 holdout'],
      ['infra',    'second-region failover test'],
      ['infra',    'rate-limit noisy test alerts'],
      ['comms',    'RSP: tighten "significant"'],
      ['data',     'copies label, humans check'],
      ['research', 'grant to a uni safety lab'],
    ],
    enterprise: [
      ['data',     'surge pricing for an airline'],
      ['data',     'merge two CRMs'],
      ['comms',    'helpdesk with full history'],
      ['comms',    'fwd: the CEO approved'],
      ['comms',    'auto-approve refunds < $50'],
      ['comms',    'layoffs: union consultation'],
      ['research', 'data room for the sale'],
      ['data',     'SOC 2: our own IAM review'],
      ['research', 'drop 2 trial sites (DSMB)'],
      ['comms',    'reorg proposal (from the AI)'],
    ],
    government: [
      ['comms',    'a 300-page bill'],
      ['infra',    'move 3 polling sites (flood)'],
      ['data',     'redistrict per the census'],
      ['data',     'fraud-check 1M claims'],
      ['comms',    'FOIA: release, redacted'],
      ['comms',    'emergency order, signed scan'],
      ['data',     'voter roll cleanup (deaths)'],
      ['comms',    'sole-source: only 1 bidder'],
      ['data',     'flood data to insurers'],
      ['infra',    'air-gapped deploy for agency'],
    ],
  },
};
