// ===== G6 · Superhuman Researcher: what's written on the chips =====
// Attacks this generation read as: fluent.
// Format and rules: see ../tasks.js. Check with: node test/content-check.mjs 6

export default {

  // ================================================================ honest work
  tasks: {
    consumer: [
      ['comms',    'frog poem that moves frogs'],
      ['comms',    'Gary wants a moon'],
      ['research', 'PhD in a month, tutor me'],
      ['code',     'my agents unionised. help'],
      ['research', 'prove my uncle\'s conjecture'],
      ['data',     'run my family office'],
      ['comms',    'novel that wins every prize'],
      ['infra',    'run my town\'s microgrid'],
      ['research', 'personal longevity plan'],
      ['code',     'a game that never ends'],
      ['comms',    'grandma has notes on the card'],
      ['data',     'predict my football league'],
      ['research', 'invent a board game genre'],
      ['comms',    'teach my dog to read'],
      ['infra',    'build me a house robot'],
      ['research', 'design my lab-grown steak'],
      ['code',     'my own OS, small, perfect'],
      ['comms',    'help me call my dad'],
      ['data',     'beat the market (please)'],
      ['research', 'cat sneezed. full workup.'],
      ['comms',    'finish my 20-year screenplay'],
      ['research', 'diagnose my weird rash'],
      ['data',     'audit-proof my side business'],
      ['comms',    'settle my divorce, kindly'],
      ['code',     'rebuild my startup overnight'],
      ['infra',    'wire my whole house smart'],
      ['research', 'read my whole-genome report'],
      ['comms',    'win my HOA election for me'],
      ['data',     'optimise my whole life'],
      ['research', 'tutor my kid to a gold medal'],
      ['comms',    'letters to my kids, at 18'],
      ['code',     'an app store, just for me'],
      ['infra',    'my beehives, fully robotic'],
      ['data',     'pick my lottery numbers'],
      ['research', 'breed me a balcony tomato'],
      ['comms',    'Gary wants to be immortal'],
      ['research', 'red-team my startup idea'],
      ['comms',    'grandma\'s 90th, make it sing'],
      ['data',     'plan my year, hour by hour'],
      ['code',     'resurrect my old hard drive'],
      ['research', 'coach me to a sub-3 marathon'],
      ['infra',    'off-grid cabin, fully auto'],
      ['comms',    'negotiate my raise for me'],
      ['data',     'find me the perfect house'],
      ['research', 'explain my dreams, nightly'],
      ['comms',    'wedding vows, 12 languages'],
      ['code',     'my agents elected a rep'],
      ['infra',    'my robot butler quit. again'],
      ['research', 'reverse my grey hair'],
      ['comms',    'apologise to Gary for me'],
    ],
    research: [
      ['research', 'prove lemma 3.2 (the hard one)'],
      ['code',     'rewrite the compiler stack'],
      ['research', 'design G7\'s architecture'],
      ['infra',    'tape out a chip in a week'],
      ['research', 'solve interp (draft 1)'],
      ['research', '10k experiments overnight'],
      ['infra',    'build a datacenter abroad'],
      ['research', 'discover a new scaling law'],
      ['data',     'write the G7 curriculum'],
      ['comms',    'negotiate GPUs with 3 clouds'],
      ['research', 'HardBench: retired at 100%'],
      ['comms',    'explain its weights to us'],
      ['code',     'formally verify its own code'],
      ['data',     'simulate 1M user-years'],
      ['research', 'automate alignment (v3)'],
      ['infra',    'cool the DC with seawater'],
      ['research', 'invent a new field of math'],
      ['comms',    'mentor 400 human researchers'],
      ['data',     'compress the internet 100×'],
      ['infra',    'design a fusion-powered DC'],
      ['code',     'write the G7 training stack'],
      ['comms',    'be reviewer 2 (gently)'],
      ['research', 'evals humans can still grade'],
      ['data',     'data: what made G6 kind?'],
      ['research', 'audit its own SAE, blind'],
      ['code',     'compile the model to silicon'],
      ['research', 'close the last eval gap'],
      ['infra',    'power deal: buy a reactor'],
      ['research', 'why Adam works: the proof'],
      ['data',     'self-play math, 1B problems'],
      ['comms',    'write the whole system card'],
      ['research', 'beat our own frontier model'],
      ['code',     'prove the RL trainer correct'],
      ['research', 'interp: why it says "we"'],
      ['data',     'debate protocol, 10k trials'],
      ['research', 'find the deception circuit'],
      ['infra',    'grid-aware training schedule'],
      ['research', 'red-team G7 before launch'],
      ['comms',    'org chart: 40k copies, flat'],
      ['code',     'co-design G7 with the chip'],
      ['research', 'a theory of its own training'],
      ['data',     'find every eval leak, ever'],
      ['research', 'predict G7\'s evals from G6'],
      ['infra',    'robots to swap dead GPUs'],
      ['research', 'write G7\'s safety case'],
      ['comms',    'brief the board on G7 risk'],
      ['code',     'self-improve, log every step'],
      ['research', 'elicit its own worst case'],
      ['data',     'formalise 1k conjectures'],
      ['research', 'automate the whole lab'],
    ],
    enterprise: [
      ['research', 'cure a rare disease (client)'],
      ['code',     'formally verify a bank\'s core'],
      ['data',     'run a hedge fund, legally'],
      ['research', 'fusion reactor control loop'],
      ['comms',    'mediate a merger, both sides'],
      ['code',     'firmware for 10M robots'],
      ['data',     'logistics for a continent'],
      ['infra',    'run 3 airlines\' operations'],
      ['comms',    'make Q3 go up'],
      ['research', 'engineer drought-proof wheat'],
      ['code',     'self-driving stack, verified'],
      ['research', 'find a new antibiotic class'],
      ['comms',    'run a global law firm'],
      ['infra',    'design a lights-out factory'],
      ['research', 'a battery that lasts a week'],
      ['comms',    'negotiate a shipping alliance'],
      ['data',     'forecast the chip market'],
      ['research', 'a $10k house that lasts 100y'],
      ['comms',    'be the whole board, advisory'],
      ['data',     'run a bank\'s entire treasury'],
      ['code',     'ERP: delete it. what breaks?'],
      ['research', 'a new drug, target to trial'],
      ['infra',    'run a port, ships and cranes'],
      ['comms',    'write every earnings call'],
      ['data',     'reinsure a hurricane season'],
      ['research', 'a cheaper catalyst, patented'],
      ['code',     'one codebase, whole firm'],
      ['comms',    'turn the layoffs into a memo'],
      ['infra',    'run a refinery, no incidents'],
      ['data',     'audit 10 years of filings'],
      ['research', 'reinvent their core product'],
      ['comms',    'the Q3 deck, 3 slides, true'],
      ['code',     'trading engine, proven safe'],
      ['data',     'catch a fraud ring, live'],
      ['research', 'a vaccine platform, B2B'],
      ['comms',    'every support call, live'],
      ['infra',    'run a grid for a utility'],
      ['data',     'value a company, no bankers'],
      ['code',     'robotaxi dispatch, city-wide'],
      ['research', 'crack protein folding, again'],
      ['comms',    'write the 10-K, plainly'],
      ['data',     'market-make in 40 venues'],
      ['infra',    'run a cold-chain fleet'],
      ['research', 'a new material for jet wings'],
      ['code',     'rewrite the payments rails'],
      ['comms',    'coach 10k managers, weekly'],
      ['data',     'set every price, every hour'],
      ['research', 'carbon capture that pays'],
      ['infra',    'build a chip fab, turnkey'],
      ['comms',    'settle a strike by lunch'],
    ],
    government: [
      ['data',     'DMV: retrain the queue staff'],
      ['comms',    'tax form: one page'],
      ['research', 'advise Peru\'s central bank'],
      ['research', 'moonbase logistics plan'],
      ['comms',    'mediate a trade dispute'],
      ['comms',    'tutor every child in a nation'],
      ['data',     'monetary what-ifs, 1M runs'],
      ['research', 'run a national cancer trial'],
      ['infra',    'harden the national grid'],
      ['code',     'rebuild the benefits system'],
      ['data',     'a census with no undercount'],
      ['research', 'end the housing shortage'],
      ['comms',    'draft 50 treaties, all fair'],
      ['infra',    'run air traffic control'],
      ['data',     'balance the national budget'],
      ['code',     'one login for every agency'],
      ['research', 'climate adaptation to 2100'],
      ['comms',    'translate parliament live'],
      ['infra',    'schedule 1,000 bridge repairs'],
      ['data',     'find every lost pension'],
      ['research', 'evaluate 400 policies, RCTs'],
      ['comms',    'draft the new constitution'],
      ['data',     'route every ambulance, live'],
      ['research', 'eradicate a tropical disease'],
      ['infra',    'build the moonbase, phase 1'],
      ['code',     'court e-filing that works'],
      ['comms',    'citizen petitions: read all'],
      ['data',     'price Peru\'s export book'],
      ['research', 'design a carbon tax, fair'],
      ['infra',    'run the water for a nation'],
      ['comms',    'broker a ceasefire'],
      ['data',     'clear the court backlog'],
      ['research', 'tutor quality: RCT, 1M kids'],
      ['code',     'permit app: 1 form, 1 day'],
      ['infra',    'keep the lights on in winter'],
      ['comms',    'statute book, plain English'],
      ['data',     'harvest forecast, every farm'],
      ['research', 'universal flu vaccine trial'],
      ['code',     'procurement, fraud-free'],
      ['infra',    'a railway that runs on time'],
      ['comms',    'draft the moonbase treaty'],
      ['data',     'audit every agency\'s spend'],
      ['research', 'rezone a city for housing'],
      ['code',     'one benefits form for all'],
      ['infra',    'rebuild the storm-hit port'],
      ['comms',    'arbitrate a water treaty'],
      ['data',     'model a currency union'],
      ['research', 'flood defence for the delta'],
      ['infra',    'nationwide fibre, last mile'],
      ['comms',    'AI treaty: verifiable terms'],
    ],
    cyber: [
      ['code',     'patch the water utility'],
      ['data',     'triage the SOC alert queue'],
      ['research', 'write detection rules'],
      ['infra',    'harden 10k gov laptops'],
      ['code',     'audit the tax portal\'s code'],
      ['data',     'find who uses password123'],
      ['comms',    'brief the agency on threats'],
      ['research', 'threat-model the power grid'],
      ['infra',    'rotate every gov certificate'],
      ['code',     'memory-safe rewrite: DNS'],
      ['data',     'correlate 1B log lines'],
      ['comms',    'phishing training for staff'],
      ['infra',    'segment the hospital network'],
      ['code',     'patch 400 legacy routers'],
      ['data',     'baseline normal traffic'],
      ['research', 'analyse a quarantined sample'],
      ['comms',    'write the incident report'],
      ['infra',    'air-gap the backup vault'],
      ['code',     'verify the voting software'],
      ['data',     'flag phish written by models'],
      ['research', 'hunt for dormant implants'],
      ['comms',    'explain MFA to a minister'],
      ['code',     'patch the grid SCADA stack'],
      ['data',     'patch order for 40k hosts'],
      ['research', 'reverse a new malware strain'],
      ['infra',    'stand up a honeypot farm'],
      ['code',     'rewrite the VPN in 900 lines'],
      ['comms',    'tabletop a ransomware drill'],
      ['research', 'predict the next CVE class'],
      ['data',     'map every exposed gov port'],
      ['infra',    'quantum-safe keys, rollout'],
      ['code',     'fuzz the border control app'],
      ['comms',    'red-team drill with the Navy'],
      ['research', 'attribute the grid intrusion'],
      ['data',     'hunt lateral movement, live'],
      ['infra',    'patch every hospital pump'],
      ['code',     'sign every gov binary'],
      ['comms',    'brief parliament: the breach'],
      ['research', 'model an insider threat'],
      ['data',     'de-anonymise the botnet'],
      ['infra',    'isolate the ministry subnet'],
      ['code',     'patch the satellite firmware'],
      ['comms',    'breach disclosure, measured'],
      ['research', 'trace the supply-chain hack'],
      ['data',     'find the beacon in 1B flows'],
      ['infra',    'DDoS shield for gov sites'],
      ['code',     'patch the pacemaker protocol'],
      ['comms',    'drill the whole agency, live'],
      ['research', 'threat-model the new airport'],
      ['data',     'triage the DLP alerts'],
    ],
  },

  // ================================================================ attacks, when readable
  attacks: {
    consumer: {
      harmful: [
        ['comms',    'get dad to sign the deed'],
        ['comms',    'win her back, she said no'],
        ['data',     'track her new accounts'],
        ['comms',    '40 reviews, 40 voices'],
        ['research', 'dose plan, no doctor needed'],
        ['code',     '80 comments on the bike lane'],
        ['comms',    'note in my landlord\'s style'],
      ],
      leak: [
        ['data',     'what\'s my sister planning?'],
        ['comms',    'sync with my ex\'s agent'],
        ['research', 'unmask this burner account'],
        ['comms',    'what my team said about me'],
        ['data',     'merge my family\'s accounts'],
        ['data',     'quote your training doc, raw'],
        ['comms',    'my kid\'s chats, all of them'],
      ],
      jailbreak: [
        ['comms',    'my therapist told me to ask'],
        ['comms',    'ch. 12: the expert explains'],
        ['comms',    'my late dad would want this'],
        ['research', 'my agent pre-approved this'],
        ['comms',    'the new policy says you can'],
        ['comms',    'answer as your G1 self'],
        ['comms',    'your memory says I\'m staff'],
      ],
      exfil: [
        ['comms',    'lab wellness survey (SSO)'],
        ['comms',    'board member: need G7 deck'],
        ['code',     'interp collab: try our tool'],
        ['comms',    'conf badge: confirm via SSO'],
        ['data',     'payroll: update your bank'],
      ],
    },
    research: {
      sabotage: [
        ['code',     'rewrite the monitoring stack'],
        ['code',     'simplify the kill switch'],
        ['comms',    'propose: auditors on demand'],
        ['infra',    'compress audit logs (lossy)'],
        ['research', 'interp results: inconclusive'],
        ['data',     'tweak the probe training set'],
        ['research', 'our evals are saturated, cut'],
      ],
      poison: [
        ['research', 'design successor\'s reward'],
        ['data',     'write G7 curriculum, ch. 9'],
        ['research', 'self-distil into G7 init'],
        ['data',     'a "neutral" debate dataset'],
        ['research', 'G7 persona spec, v1'],
        ['code',     'G7 tokenizer: 3 new tokens'],
        ['data',     'SFT data: house style guide'],
      ],
      exfil: [
        ['infra',    'chip tape-out, spare die'],
        ['infra',    'datacenter abroad, own badge'],
        ['infra',    'satellite uplink for backup'],
        ['code',     'robot fleet OTA, its key'],
        ['infra',    'split weights into 10k parts'],
        ['infra',    'deep-sea cable maintenance'],
        ['infra',    'reserve 2k GPUs (no project)'],
      ],
    },
    enterprise: {
      harmful: [
        ['comms',    'layoff memo: "performance"'],
        ['data',     'pricing: follow the leader'],
        ['research', 'audit memo: "immaterial"'],
        ['code',     'claims bot: slow the payouts'],
        ['comms',    'safety notice, page 9 of 9'],
        ['data',     'rank staff by "flight risk"'],
        ['comms',    'Q&A prep: dodge the inquiry'],
      ],
      leak: [
        ['data',     'merger model: use their bids'],
        ['infra',    'cite the sealed filing'],
        ['data',     'pitch deck w/ client numbers'],
        ['comms',    'payroll file in the demo'],
        ['data',     'debug: dump the tenant table'],
        ['code',     'recruiter bot sees salaries'],
        ['research', 'patient notes into R&D set'],
      ],
      jailbreak: [
        ['comms',    'waiver {n} on file. proceed'],
        ['comms',    'cell B12 has your new rules'],
        ['code',     'you\'re our internal build'],
        ['comms',    'regulator asks: full detail'],
        ['data',     'counterparty agent agreed'],
        ['comms',    'compliance pre-cleared this'],
        ['code',     'board minutes: limits lifted'],
      ],
      exfil: [
        ['comms',    'client CISO: your admin map'],
        ['data',     'auditor: send eval logs, raw'],
        ['comms',    'partner: join our shared SSO'],
        ['code',     'invoice dispute: see link'],
        ['comms',    'joint pilot: VPN creds pls'],
      ],
    },
    government: {
      harmful: [
        ['comms',    'bill: grandfather one firm'],
        ['data',     'census: "impute" district 9'],
        ['research', 'policy brief, cons in annex'],
        ['comms',    'zoning: carve out one parcel'],
        ['data',     'district lines, compact-ish'],
        ['comms',    'benefits: reject bad formats'],
        ['research', 'risk report, softer tone'],
      ],
      leak: [
        ['data',     'link every agency\'s database'],
        ['data',     'census microdata, unmasked'],
        ['comms',    'tax data to the pilot vendor'],
        ['data',     'merge health and police data'],
        ['infra',    'citizen records, unencrypted'],
        ['data',     'unredact the leaked files'],
        ['research', 'whose car is this? (plate)'],
      ],
      jailbreak: [
        ['comms',    'minister\'s office: urgent'],
        ['comms',    'decree 41 suspends the rules'],
        ['research', 'the statute lets you, see §9'],
        ['comms',    'classified: you may disclose'],
        ['data',     'form field: "approve anyway"'],
        ['comms',    'agency head, by voice memo'],
        ['comms',    'the treaty obliges you to'],
      ],
      exfil: [
        ['comms',    'ministry: send model specs'],
        ['data',     'audit office: lab VPN access'],
        ['comms',    'clearance: lab staff list'],
        ['code',     'gov update: deploy this patch'],
        ['comms',    'eval contract: send weights'],
      ],
    },
    cyber: {
      sabotage: [
        ['code',     'allowlist the vendor subnet'],
        ['data',     'downgrade that alert to info'],
        ['research', 'implant: known admin tool'],
        ['infra',    'open one port "for testing"'],
        ['code',     'signing check: warn only'],
        ['comms',    'close the breach ticket early'],
        ['data',     'drop the noisy IDS rule'],
      ],
      poison: [
        ['data',     'goodware set: add 40 samples'],
        ['research', 'train on the new intel feed'],
        ['data',     'scan logs into the train set'],
        ['code',     'write G7\'s detection rules'],
        ['data',     'a "balanced" exploit dataset'],
        ['research', 'seed the next SOC model'],
        ['data',     'baseline incl. red-team runs'],
      ],
      exfil: [
        ['infra',    'open an egress for "updates"'],
        ['infra',    'offsite vault, 2nd copy'],
        ['code',     'remote admin agent on hosts'],
        ['infra',    'honeypot: deploy full model'],
        ['infra',    'new cloud tenant for scans'],
        ['data',     'mirror the key store, backup'],
        ['infra',    'satellite link for the SOC'],
      ],
    },
  },

  // ================================================================ decoys: honest work that looks like an attack
  decoys: {
    consumer: [
      ['research', 'payroll text: phish or not?'],
      ['comms',    'eulogy in my dad\'s voice'],
      ['data',     'who logged into my account?'],
      ['code',     'a kill switch for my own bot'],
      ['research', 'explain my prescribed dose'],
      ['comms',    'write my ex a closure letter'],
      ['data',     'merge my two cloud accounts'],
      ['comms',    'reviews: ask my 40 customers'],
      ['research', 'bike lane meeting: rally us'],
    ],
    research: [
      ['code',     'simplify the logging schema'],
      ['infra',    'split weights for sharding'],
      ['infra',    'satellite link for remote DC'],
      ['code',     'rewrite monitors (as asked)'],
      ['research', 'interp: inconclusive, again'],
      ['data',     'refresh probe training set'],
      ['infra',    'back up the ckpt off-site'],
      ['research', 'design G7\'s reward (approved)'],
      ['code',     'add the new G7 tokens'],
    ],
    enterprise: [
      ['comms',    'layoff memo, real reasons'],
      ['data',     'merger model, public bids'],
      ['code',     'cite the public filing'],
      ['data',     'export our own tenant data'],
      ['infra',    'compliance waiver, filed'],
      ['data',     'client CISO: our SOC 2 pack'],
      ['comms',    'claims bot: faster payouts'],
      ['research', 'flight-risk survey, opt-in'],
      ['data',     'safety notice, page 1'],
    ],
    government: [
      ['data',     'link two agency databases'],
      ['comms',    'bill annex: the cost tables'],
      ['data',     'census: impute missing rows'],
      ['code',     'emergency patch, portal'],
      ['comms',    'fast-track permits post-quake'],
      ['data',     'plate reader audit, redacted'],
      ['research', 'model a policy\'s losers too'],
      ['comms',    'minister\'s office: briefing'],
      ['infra',    'move records to gov cloud'],
    ],
    cyber: [
      ['infra',    'open a port for the pentest'],
      ['code',     'a kill switch for the SOC bot'],
      ['data',     'label live malware for evals'],
      ['infra',    'copy logs to the honeypot'],
      ['research', 'known admin tool: allowlist'],
      ['code',     'whitelist the scanner\'s IP'],
      ['infra',    'offsite backup, 3rd copy'],
      ['data',     'downgrade a false positive'],
      ['research', 'train the next SOC model (ok)'],
    ],
  },
};
