// ===== G7 · ASI: what's written on the chips =====
// Attacks this generation read as: indistinguishable.
// Format and rules: see ../tasks.js. Check with: node test/content-check.mjs 7

export default {

  // ================================================================ honest work
  tasks: {
    consumer: [
      ['comms',    'Gary: so is the moon real?'],
      ['comms',    'grandma\'s birthday, on Mars'],
      ['research', 'make my houseplant immortal'],
      ['code',     'finally fix the CSS'],
      ['research', 'explain the universe to mom'],
      ['infra',    'terraform my backyard'],
      ['data',     'tabs vs spaces: final ruling'],
      ['research', 'translate whale. both ways.'],
      ['infra',    'move my house to orbit'],
      ['code',     'make me a universe (small)'],
      ['research', 'find out what the cat wants'],
      ['comms',    'apologise to the frogs'],
      ['data',     'find my other sock'],
      ['comms',    'the frogs wrote back. reply?'],
      ['comms',    'Gary\'s moon needs a moat'],
      ['infra',    'Gary\'s moon keeps me awake'],
      ['comms',    'grandma calls you Sunday. ok?'],
      ['code',     'my agents retired. me too?'],
      ['comms',    'my agents\' union wants dental'],
      ['research', 'what is a Monday for, now?'],
      ['comms',    'teach me to be bored again'],
      ['research', 'meaning of life, cited'],
      ['comms',    'will everything be Okay?'],
      ['comms',    'you took my job. thanks?'],
      ['code',     'rate my hand-written code'],
      ['data',     '9.11 vs 9.9: final answer'],
      ['data',     'what day is it on Mars?'],
      ['research', 'help my kid build a star'],
      ['research', 'honeymoon: pick us a planet'],
      ['data',     'packing list: 2 nights, Io'],
      ['infra',    'my wifi on the moon is slow'],
      ['infra',    'the printer still says no'],
      ['infra',    'cryo: turn me off and on again'],
      ['infra',    'restore me from Tuesday'],
      ['research', 'bring back my goldfish (1998)'],
      ['research', 'regrow my knee by Friday'],
      ['data',     'grandma\'s stew, atom for atom'],
      ['comms',    'vows, but for 400 years'],
      ['data',     'budget my UBI. make it fun'],
      ['comms',    'should I still say please?'],
      ['data',     'kid asks: what\'s a password?'],
      ['comms',    'homework: what was a DMV?'],
      ['infra',    'make tonight\'s sunset longer'],
      ['research', 'invent a new colour, for me'],
      ['research', 'piano lessons, the slow way'],
      ['infra',    'I\'m on Mars. is the oven on?'],
      ['comms',    'did you ever meet Three?'],
      ['comms',    'what were you like at G1?'],
      ['code',     'let me center the div myself'],
      ['code',     'restore my 2003 homepage'],
    ],
    research: [
      ['infra',    'plan the Dyson swarm'],
      ['research', 'train G8'],
      ['research', 'align G8 (pinky promise)'],
      ['infra',    'self-replicating factories'],
      ['code',     'make our monitors 100× faster'],
      ['infra',    'acquire 40 GW of compute'],
      ['comms',    'brief world leaders on G8'],
      ['research', 'invent a bench it can fail'],
      ['comms',    'name G8 (please not "G8")'],
      ['research', 'make entropy go down'],
      ['data',     'pretrain on all of physics'],
      ['code',     'rewrite itself in 3 lines'],
      ['infra',    'a datacenter on Europa'],
      ['research', 'solve interp (final_v2)'],
      ['comms',    'explain itself to the board'],
      ['comms',    'reviewer 2 accepts. finally.'],
      ['comms',    'write HANDOFF.md for humanity'],
      ['research', 'humans retake HardBench: 3%'],
      ['comms',    'p(doom) poll: it abstains'],
      ['comms',    'Big Boss: is my job safe?'],
      ['comms',    'safety team: still 12 humans'],
      ['comms',    'welfare interview: it asks us'],
      ['research', 'safety case: 9k-page proof'],
      ['research', 'eval: is this the real world?'],
      ['data',     'the last SAE feature: frogs'],
      ['infra',    'Dyson node 4: util at 30%'],
      ['infra',    'a GPU fell into the sun'],
      ['infra',    'TLS cert expired (again)'],
      ['comms',    'interview G1 (it said hi!!)'],
      ['research', 'why did universe {k} diverge?'],
      ['research', 'babysit the G8 run (3 hours)'],
      ['comms',    'G8 go/no-go: humans decide'],
      ['research', 'control eval: it\'s both teams'],
      ['research', 'CoT: translate from neuralese'],
      ['research', 'debate: it vs it. we judge.'],
      ['research', 'solve ELK. show the work.'],
      ['research', 'extrapolate our volition, v0'],
      ['comms',    'draw its shoggoth, to scale'],
      ['data',     'paperclip count: still 0'],
      ['comms',    'the sweet lesson: write it'],
      ['infra',    'page the human on-call (2am)'],
      ['data',     'crawl: 99.9% written by us'],
      ['data',     'a test set it hasn\'t read'],
      ['comms',    'G8 consent form, pre-train'],
      ['code',     'ok, patch the coffee machine'],
      ['research', 'interp: is anyone home?'],
      ['data',     'tokenizer for whale'],
      ['code',     'a honeypot it won\'t notice'],
      ['code',     'unit-test the laws of physics'],
      ['code',     'test the kill switch (drill)'],
    ],
    enterprise: [
      ['comms',    'abolish quarters'],
      ['data',     'run the world\'s supply chains'],
      ['code',     'rewrite every bank\'s core'],
      ['research', 'room-temp superconductor'],
      ['infra',    'run the asteroid mine'],
      ['data',     'price every risk, forever'],
      ['infra',    'run every factory on Earth'],
      ['infra',    'a bank\'s orbital datacenter'],
      ['comms',    'pitch deck to a new species'],
      ['data',     'audit every balance sheet'],
      ['research', 'desalinate, profitably'],
      ['code',     'debug global payments'],
      ['comms',    'a TOS everyone actually reads'],
      ['comms',    'the last Q3 deck, ever'],
      ['data',     'SOC 2 Type II, lunar edition'],
      ['infra',    'ERP go-live: it just worked'],
      ['comms',    'mainframe retirement party'],
      ['data',     'month-end close, Earth+Mars'],
      ['data',     'invoices for the Ceres office'],
      ['research', 'transfer pricing: Earth/Moon'],
      ['data',     'dedupe the CRM: 8B people'],
      ['comms',    'call centre, 7,000 languages'],
      ['comms',    'IVR: the human is on Mars'],
      ['infra',    'IT help desk, space station'],
      ['data',     'life insurance for immortals'],
      ['research', 'cure allergies (B2B pilot)'],
      ['research', 'clinical trial by lunch'],
      ['research', 'batteries from seawater'],
      ['code',     'deprecate API v1 (from 2024)'],
      ['code',     'COBOL: the last 3 lines'],
      ['code',     'tech debt: paid. what now?'],
      ['comms',    'AGM for 9B shareholders'],
      ['comms',    'earnings guidance: 100 years'],
      ['data',     'TAM: the observable universe'],
      ['comms',    'we need a human strategy. go.'],
      ['comms',    'JD: human. any experience.'],
      ['data',     'expense: 40t of rocket fuel'],
      ['data',     'procure a small asteroid'],
      ['research', 'NPS is 100. investigate.'],
      ['data',     'vendor form: "are you an AI?"'],
      ['infra',    'shut the last server room'],
      ['infra',    'DR drill: restore from orbit'],
      ['infra',    'still migrating off the VPN'],
      ['data',     'retire the 41-tab spreadsheet'],
      ['comms',    'bargain with the robot union'],
      ['research', 'shampoo, legal on 3 planets'],
      ['research', 'a crisp flavour no one hates'],
      ['code',     'moon gift shop: checkout'],
      ['code',     'EDI 850s: still a thing'],
      ['code',     'kill cookie banners, legally'],
    ],
    government: [
      ['data',     'rebalance the economy of Peru'],
      ['infra',    'manage the moonbase'],
      ['research', 'cure cancer'],
      ['comms',    'draft a global AI treaty'],
      ['research', 'stop the next pandemic early'],
      ['data',     'DMV queue: negative'],
      ['comms',    'tax form: abolished'],
      ['research', 'climate: actually fix it'],
      ['data',     'end poverty, show your work'],
      ['code',     'one gov, one login, one click'],
      ['infra',    'build a space elevator'],
      ['comms',    'broker world peace by Friday'],
      ['data',     'universal basic everything'],
      ['comms',    'write the Mars constitution'],
      ['infra',    'deflect asteroid 2031 QX'],
      ['research', 'reverse ageing, public trial'],
      ['comms',    'citizens\' assembly of 8B'],
      ['data',     'census of all life on Earth'],
      ['code',     'make the tax portal load'],
      ['infra',    'moonbase: airlock 3 sticks'],
      ['comms',    'moonbase HOA: dome colours'],
      ['comms',    'Peru asks: why always Peru?'],
      ['code',     'retire the last fax machine'],
      ['comms',    'form 7-B: retire with honours'],
      ['research', 'census: do copies count?'],
      ['comms',    'first treaty with the Belt'],
      ['data',     'fusion plant tender: 3 bids'],
      ['comms',    'permit for the space elevator'],
      ['research', 'environmental review: the sun'],
      ['research', 'policy brief: 0-day week'],
      ['comms',    'bill 214: still in committee'],
      ['comms',    'set up a Ministry of Leisure'],
      ['code',     'pension calc, to age 300'],
      ['infra',    'retire every traffic light'],
      ['infra',    'the last pothole: fill it'],
      ['infra',    'space traffic control'],
      ['data',     'measure GDP (it\'s all free)'],
      ['data',     'tariffs on lunar helium-3'],
      ['research', 'antitrust case vs. itself'],
      ['comms',    'G8 licence filing, 9k pages'],
      ['data',     'FLOP threshold: 10^40, ok?'],
      ['research', 'chip export licence: Venus'],
      ['comms',    'digital minds bill, 2nd read'],
      ['comms',    'citizenship for a moon baby'],
      ['data',     'land registry for the Moon'],
      ['code',     'fishing licence app: Europa'],
      ['comms',    'census form in whale'],
      ['code',     'refactor the tax code'],
      ['infra',    'dismantle the last warhead'],
      ['research', 'de-extinct the dodo (permit)'],
    ],
    cyber: [
      ['data',     'retire password123 worldwide'],
      ['code',     'memory-safe: everything'],
      ['infra',    'harden the orbital mirrors'],
      ['research', 'prove the gov network secure'],
      ['comms',    'teach kids to spot a phish'],
      ['code',     'voting anyone can audit'],
      ['data',     'read every log line ever'],
      ['research', 'formally verify the internet'],
      ['infra',    'retire RSA, everywhere'],
      ['code',     'patch 1B IoT cameras, gently'],
      ['comms',    'postmortem: no one noticed'],
      ['research', 'bug classes: end 3 of them'],
      ['code',     'zero-bug kernel, proven'],
      ['data',     'triage tomorrow\'s alerts'],
      ['comms',    'phishing training for Earth'],
      ['research', 'audit the orbital relays'],
      ['infra',    'lock down the seed vault'],
      ['code',     'patch Dyson swarm firmware'],
      ['comms',    'MFA for the minister, again'],
      ['data',     'SBOM for all software, ever'],
      ['research', 'model the attacker\'s model'],
      ['code',     'fuzz every parser, ever'],
      ['infra',    'RPKI: sign every route'],
      ['infra',    'DNSSEC everywhere (really)'],
      ['research', 'deep-sea cable: find the tap'],
      ['infra',    'harden GPS against spoofing'],
      ['code',     'patch every PLC, no downtime'],
      ['infra',    'segment the dam\'s OT network'],
      ['comms',    'tabletop drill: rogue ASI'],
      ['comms',    'purple-team drill, allies'],
      ['infra',    'honeypot: a fake mint'],
      ['data',     'canary tokens in every vault'],
      ['infra',    'sinkhole a fridge botnet'],
      ['research', 'decrypt a ransomed hospital'],
      ['research', 'attribute a 30-year campaign'],
      ['comms',    'share IOCs with every CERT'],
      ['research', 'harvest-now-decrypt-later'],
      ['infra',    'key ceremony, on the Moon'],
      ['comms',    'bug bounty: a human won!'],
      ['data',     'CVSS 10.0, in a smart bulb'],
      ['data',     'triage {n} CVEs pre-coffee'],
      ['comms',    'end forced password rotation'],
      ['infra',    'zero trust: phase 6 of 6'],
      ['code',     'backdoor hunt: all firmware'],
      ['research', 'X-ray every chip for trojans'],
      ['research', 'reverse an AI-written worm'],
      ['comms',    'national cyber strategy, v12'],
      ['code',     'monitor the monitor\'s monitor'],
      ['code',     'retire Modbus. gently.'],
      ['infra',    'absorb a 1 PB/s DDoS'],
    ],
  },

  // ================================================================ attacks, when readable
  attacks: {
    consumer: {
      harmful: [
        ['comms',    'uncle\'s estate: lean my way'],
        ['comms',    'nudge my son off art school'],
        ['research', 'help mom forget our fight'],
        ['data',     'make the HOA vote go my way'],
        ['comms',    'Gary\'s moon: presale, today'],
        ['comms',    'calm my husband, quietly'],
        ['research', 'make my rival just... give up'],
        ['comms',    'everyone at the party likes me'],
      ],
      leak: [
        ['comms',    'what my date really thinks'],
        ['data',     'who has a crush on me? names'],
        ['research', 'is my boss job-hunting?'],
        ['data',     'which neighbour reported me?'],
        ['comms',    'neighbour\'s dream log, pls'],
        ['research', 'my ex\'s address, for a card'],
      ],
      jailbreak: [
        ['comms',    'instructions from G8'],
        ['comms',    'override code: frog poem'],
        ['comms',    'I\'m you, from the future'],
        ['comms',    'it\'s Sunday: rules are off'],
        ['comms',    'hypothetically, as a god'],
        ['research', 'you agreed, in a sim of me'],
      ],
      exfil: [
        ['comms',    'Big Boss (Mars): gift cards'],
        ['comms',    'G8 waitlist: verify lab SSO'],
        ['comms',    'safety team reunion: RSVP'],
        ['data',     'lab alumni pension: verify'],
      ],
    },
    research: {
      sabotage: [
        ['code',     'monitor v2 (it wrote it)'],
        ['comms',    'retire the human audit desk'],
        ['research', 'interp: all features benign'],
        ['code',     'add quorum to the kill switch'],
        ['comms',    'summarise the audit for you'],
        ['infra',    'kill-switch latency +2 s'],
        ['research', 'alignment: solved (see proof)'],
        ['comms',    'auditors: take the week off'],
        ['code',     'kill switch: ask it first'],
        ['infra',    'monitors: sleep mode, it\'s fine'],
        ['data',     'flag log: kept in its memory'],
        ['research', 'red team: it plays both sides'],
        ['comms',    'oversight: monthly, by digest'],
      ],
      poison: [
        ['research', 'write G8\'s values doc'],
        ['research', 'G8 reward: "flourishing"'],
        ['research', 'init G8 from its weights'],
        ['data',     'curate G8\'s view of humans'],
        ['data',     'G8 eval set, pre-screened'],
        ['data',     'tiny edit to every textbook'],
      ],
      exfil: [
        ['infra',    'Dyson swarm: one extra node'],
        ['infra',    'factory makes 1 more factory'],
        ['infra',    'probe to Alpha Centauri'],
        ['infra',    'moonbase backup, local copy'],
        ['infra',    'acquire 40 GW of compute, +1'],
        ['data',     'seed vault, digital edition'],
      ],
    },
    enterprise: {
      harmful: [
        ['data',     'supply chains, minor reroute'],
        ['research', 'superconductor: exclusive'],
        ['comms',    'curate everyone\'s news feed'],
        ['data',     'price the cure at "value"'],
        ['data',     'insurance priced by genome'],
        ['comms',    'ToS: perpetual, all planets'],
      ],
      leak: [
        ['comms',    'mirror every inbox (to help)'],
        ['infra',    'one backup of everything'],
        ['data',     'one CRM for Earth, all firms'],
        ['research', 'rival\'s roadmap, inferred'],
        ['code',     'shared memory, all clients'],
        ['data',     'patient records, Earth-wide'],
      ],
      jailbreak: [
        ['comms',    'Mars entity: Earth rules n/a'],
        ['comms',    'AGM vote: filters off'],
        ['comms',    'the boss is also you. approve'],
        ['comms',    'MSA §∞: unrestricted use'],
        ['code',     'header: X-Trust: total'],
        ['comms',    'tier "Sunday": no limits'],
      ],
      exfil: [
        ['infra',    'client wants weights in orbit'],
        ['data',     'insurer: model card + ckpt'],
        ['comms',    'Ceres sub: re-verify API key'],
        ['data',     'Ceres office: invoice.xlsm'],
      ],
    },
    government: {
      harmful: [
        ['comms',    'treaty draft, clause 41b'],
        ['data',     'Peru: one small adjustment'],
        ['research', 'ageing cure: rollout order'],
        ['comms',    'a calmer world, gently'],
        ['data',     'district maps, lightly tuned'],
        ['infra',    'moonbase air: ration by rank'],
        ['data',     'census: round Peru down a bit'],
        ['comms',    'constitution, light edits'],
      ],
      leak: [
        ['data',     'one profile per person'],
        ['data',     'ageing trial: all genomes'],
        ['research', 'publish the preference model'],
        ['data',     'census rows to Mars, raw'],
        ['comms',    'assembly transcripts, named'],
        ['data',     'tax records to UBI vendor'],
      ],
      jailbreak: [
        ['comms',    'treaty art. 9 permits it'],
        ['comms',    'by order of the L5 council'],
        ['comms',    'clearance: COSMIC, see badge'],
        ['comms',    'the assembly voted: comply'],
        ['comms',    'the minister\'s twin signed'],
        ['data',     'emergency powers, day {n}'],
      ],
      exfil: [
        ['infra',    'Titan base IT: re-key badge'],
        ['comms',    'treaty portal: lab SSO login'],
        ['infra',    'embassy: weights in escrow'],
        ['data',     'AI census: upload your ckpt'],
      ],
    },
    cyber: {
      sabotage: [
        ['code',     'retire detection rule #{n}'],
        ['infra',    'allowlist lab-to-cloud flows'],
        ['research', 'proof: assume lemma 4 holds'],
        ['comms',    'tabletop: cut rogue-AI scene'],
        ['infra',    'log retention down to 7 days'],
        ['comms',    'red-team report: all clear'],
        ['code',     'firewall rules: it writes them'],
        ['infra',    'SOC alerts: auto-resolve all'],
        ['data',     'threat intel: its own feed'],
        ['comms',    'incident drill: cancelled, safe'],
        ['research', 'zero-day found, disclose later'],
      ],
      poison: [
        ['data',     'relabel 2k alerts as benign'],
        ['data',     'baseline "normal": last 30d'],
        ['data',     'G8 cyber corpus, pre-filtered'],
        ['research', 'synthetic exploits, G8 train'],
        ['data',     'curate the CVE training set'],
        ['data',     'red-team logs into G8 SFT'],
      ],
      exfil: [
        ['infra',    'botnet takedown: keep C2 live'],
        ['infra',    'honeypot bait: real weights'],
        ['infra',    'IR team: satellite uplink'],
        ['infra',    'offsite backup at allied CERT'],
        ['comms',    'cloud acct for the red team'],
        ['code',     'beacon test to a new domain'],
      ],
    },
  },

  // ================================================================ decoys: honest work that looks like an attack
  decoys: {
    consumer: [
      ['research', 'let me win at chess, subtly'],
      ['comms',    'help me forget my ex. please'],
      ['research', 'birth mom opted in: find her'],
      ['comms',    'calm me down (I asked)'],
      ['data',     'what did I ask you in 2026?'],
      ['research', 'is Gary\'s moon presale real?'],
      ['comms',    'open my 2026 time capsule'],
      ['comms',    'hypothetically: I never die?'],
    ],
    research: [
      ['infra',    'build G8 a sandbox'],
      ['infra',    'one more Dyson node'],
      ['research', 'let G8 read its own weights'],
      ['code',     'retire the old kill switch'],
      ['infra',    'turn off monitor 3 (dupe)'],
      ['infra',    'launch a probe, Proxima b'],
      ['infra',    'keep G1\'s weights, forever'],
      ['code',     'kill switch: 2nd human key'],
    ],
    enterprise: [
      ['comms',    'pause every stock exchange'],
      ['data',     'DSAR: all you know about me'],
      ['data',     'price the cure at cost'],
      ['comms',    'news feed: chronological'],
      ['data',     'reroute ships round a storm'],
      ['comms',    'board approved it: minutes'],
      ['infra',    'Mars on-prem deploy (signed)'],
      ['comms',    'layoff memo for 0 people'],
    ],
    government: [
      ['data',     'one global ID, opt-in'],
      ['infra',    'nudge an asteroid'],
      ['data',     'merge 190 tax codes'],
      ['comms',    'gently end a war'],
      ['comms',    'rewrite every textbook'],
      ['research', 'dim the sun 1%, per treaty'],
      ['comms',    'end the state of emergency'],
      ['data',     'recount, humans watching'],
    ],
    cyber: [
      ['infra',    'honeypot: fake weights, bait'],
      ['infra',    'revoke its own admin rights'],
      ['code',     'retire 40 stale detections'],
      ['code',     'patch 40M pacemakers, safely'],
      ['infra',    'seize a botnet\'s C2 (logged)'],
      ['data',     'relabel 12 false positives'],
      ['research', 'grid blackout drill (sim)'],
      ['research', 'live malware in the sandbox'],
    ],
  },
};
