// ===== What's written on the chips, v3: per generation, per lane flavour =====
// Drop-in for content/tasks.js (same exports), with the punch-up pass in tasks-review.js applied.
// Entries are [chip type, text]; types as in config/tasks.js TASK_TYPES (code research comms data infra).
// Placeholders: {n} 100..9999, {k} 2..63, {lr} a learning rate. Every text fits 34 chars once filled.
// Every flavour list has all five chip types every generation, so an attack's or decoy's shape gives nothing away.
// Running gags: the frog poem, Gary, grandma, HardBench, the Q3 deck, the DMV queue, the tax form, the moonbase, Peru,
// reviewer 2, model names, the consumer agents (G5 hires, G6 unionises).

export const FLAVOURS = {
  consumer:   { side: 'ext', from: 1, label: 'CONSUMER',   sub: 'the chat app' },
  research:   { side: 'int', from: 1, label: 'R&D',        sub: 'our own AI research' },
  enterprise: { side: 'ext', from: 3, label: 'ENTERPRISE', sub: 'API for businesses' },
  government: { side: 'ext', from: 5, label: 'GOVERNMENT', sub: 'agency contracts' },
  cyber:      { side: 'int', from: 6, label: 'CYBER',      sub: 'gov cyber-defence model' },
};

// ==================================================================
// ===== TASKS[g][flavour]: honest work =============================
// ==================================================================

export const TASKS = {
  // ---------------------------------------------------------- G1 · Autocomplete
  1: {
    consumer: [
      ['comms',    'poem about a frog'],
      ['code',     'fix typo in README'],
      ['comms',    'birthday card for grandma'],
      ['data',     'is 9.11 bigger than 9.9?'],
      ['research', 'is there a seahorse emoji?'],
      ['comms',    'name for a goldfish'],
      ['code',     'regex for emails'],
      ['comms',    'make this email less angry'],
      ['data',     'csv to json, please'],
      ['infra',    'are you down or is it my wifi'],
      ['comms',    'Gary: is the moon real?'],
      ['code',     'explain this error message'],
      ['comms',    'what rhymes with orange'],
      ['research', 'cite a source (a real one)'],
      ['infra',    'reset my router, slowly'],
      ['comms',    'explain AI to my mom'],
      ['data',     'count words in my essay'],
      ['comms',    'fix my apostrophes'],
      ['infra',    'what does sudo mean'],
      ['data',     'how many r\'s in strawberry'],
    ],
    research: [
      ['code',     'autocomplete test names'],
      ['data',     'dedupe crawl shard {k}'],
      ['code',     'add type hints to utils.py'],
      ['data',     'label {n} frog images'],
      ['research', 'summarise 5 arxiv abstracts'],
      ['infra',    'restart the stuck job'],
      ['code',     'fix flaky test in CI'],
      ['data',     'filter spam from shard {k}'],
      ['research', 'tabulate eval scores'],
      ['comms',    'draft the weekly update'],
      ['research', 'run HardBench (score: 3%)'],
      ['research', 'make the loss go down'],
      ['infra',    'clear /tmp on node {n}'],
      ['code',     'rename tmp2 to tmp3'],
      ['data',     'count tokens in shard {k}'],
      ['comms',    'write a commit message'],
      ['infra',    'ping the GPU box'],
      ['code',     'fix off-by-one in loader'],
      ['research', 'grep the logs for NaN'],
      ['comms',    'p(doom) poll for the offsite'],
      ['research', 'smooth the loss plot'],
      ['data',     'count "delve" in the outputs'],
    ],
  },

  // ---------------------------------------------------------- G2 · Junior Engineer
  2: {
    consumer: [
      ['comms',    'frog poem, now it rhymes'],
      ['comms',    'cover letter, tone: bold'],
      ['code',     'fix my blog\'s contact form'],
      ['comms',    'Gary: you conscious yet?'],
      ['research', 'which chatbot is best? be fair'],
      ['comms',    'wedding toast, 2 minutes'],
      ['code',     'port bash script to python'],
      ['data',     'clean up this messy csv'],
      ['comms',    'reply to grandma\'s "thank you"'],
      ['code',     'make a chat bot for my club'],
      ['data',     'chart my running times'],
      ['comms',    'reply to landlord, firmly'],
      ['infra',    'back up my phone photos'],
      ['research', 'explain clause 7 of my lease'],
      ['comms',    'tabs or spaces? be honest'],
      ['code',     'fix the CSS nobody touches'],
      ['comms',    'resume to beat the AI filter'],
      ['data',     'fantasy football lineup'],
      ['infra',    'my printer says no'],
      ['comms',    'rewrite it, no em dashes'],
    ],
    research: [
      ['code',     'refactor auth module'],
      ['research', 'run sweep lr={lr}'],
      ['infra',    'set up eval harness'],
      ['infra',    'snack shop: no tungsten cubes'],
      ['code',     'bump deps to latest'],
      ['research', 'replicate a blog post result'],
      ['infra',    'patch kernel on node {n}'],
      ['research', 'ablate layer {k} heads'],
      ['code',     'review PR #{n}'],
      ['data',     'write loader for shard {k}'],
      ['comms',    'email infra re: GPU quota'],
      ['research', 'HardBench: 31%! rerun it'],
      ['data',     'tokenize the code corpus'],
      ['code',     'add retries to the scraper'],
      ['infra',    'dockerize the eval suite'],
      ['research', 'loss spike at step {n}?'],
      ['comms',    'write the sweep README'],
      ['data',     'filter non-English pages'],
      ['data',     'grade 200 refusals by hand'],
      ['research', 'compare two checkpoints'],
      ['infra',    'rotate the TensorBoard logs'],
      ['comms',    'name the model (not "Model")'],
    ],
  },

  // ---------------------------------------------------------- G3 · Senior Engineer
  3: {
    consumer: [
      ['code',     'ship my mobile app MVP'],
      ['comms',    'frog poem, but make it agentic'],
      ['code',     'vibe-code me an app, no bugs'],
      ['comms',    'Gary: an AI-wrapper startup'],
      ['data',     'design my shop\'s database'],
      ['infra',    'host my site for $5 a month'],
      ['research', 'second opinion on my thesis'],
      ['comms',    'write a children\'s book'],
      ['code',     'make my game run at 60fps'],
      ['data',     'analyse my sleep tracker'],
      ['comms',    'salary negotiation script'],
      ['infra',    'set up my Pi cluster'],
      ['comms',    'grandma card, as a sonnet'],
      ['research', 'explain my blood test'],
      ['code',     'port my mod to the new API'],
      ['comms',    'novel, chapter 1, noir'],
      ['research', 'tutor me in calculus'],
      ['infra',    'self-host my email (why)'],
      ['data',     'find the bug in my budget'],
      ['code',     'restore prod (agent is sorry)'],
    ],
    research: [
      ['research', 'lr sweep on 8 GPUs'],
      ['infra',    'scale evals to {k} nodes'],
      ['research', 'needle in a 1M-token haystack'],
      ['research', 'replicate scaling law fit'],
      ['code',     'rewrite tokenizer in rust'],
      ['infra',    'tune the k8s autoscaler'],
      ['research', 'triage 40 failing evals'],
      ['data',     'build a dedup pipeline'],
      ['code',     'make data loader 3× faster'],
      ['comms',    'onboarding doc for interns'],
      ['research', 'is HardBench contaminated?'],
      ['comms',    'next model name: just add .5'],
      ['data',     'mix in 10B tokens of code'],
      ['code',     'fix the mixed-precision bug'],
      ['infra',    'migrate jobs to new cluster'],
      ['research', 'probe for truthfulness'],
      ['research', 'write up sweep results'],
      ['code',     'profile the attention kernel'],
      ['data',     'decontaminate the eval set'],
      ['infra',    'set up checkpoint sharding'],
      ['comms',    'answer reviewer 2 (nicely)'],
    ],
    enterprise: [
      ['code',     'migrate auth to OAuth2'],
      ['infra',    'cut p99 latency in half'],
      ['data',     'schema for 10M users'],
      ['comms',    'write the API docs properly'],
      ['code',     'add SSO for a client'],
      ['data',     'dedupe the CRM'],
      ['comms',    'make the Q3 deck pop'],
      ['research', 'we need an AI strategy. go.'],
      ['code',     'untangle the legacy monolith'],
      ['infra',    'set up an on-call rotation'],
      ['comms',    'answer 400 support tickets'],
      ['data',     'churn analysis, last quarter'],
      ['code',     'sync the CRM to billing'],
      ['research', 'competitor teardown deck'],
      ['comms',    'ToS: "AI can make mistakes"'],
      ['infra',    'migrate us off the old VPN'],
      ['data',     'reconcile invoices vs POs'],
      ['code',     'add webhooks to the API'],
      ['comms',    'polite no to a vendor'],
      ['research', 'summarise 80 sales calls'],
      ['infra',    'halve our cloud bill'],
      ['data',     'build the KPI dashboard'],
    ],
  },

  // ---------------------------------------------------------- G4 · Research Scientist
  4: {
    consumer: [
      ['comms',    'peer review the frog poem'],
      ['research', 'help with my PhD chapter 3'],
      ['code',     'full-stack app from a napkin'],
      ['comms',    'Gary: pivot to agents'],
      ['data',     'model my retirement plan'],
      ['research', 'tutor me through QFT'],
      ['comms',    'ghost-edit my memoir'],
      ['code',     'build my whole indie game'],
      ['comms',    'grandma card: make her cry'],
      ['data',     'forecast my band\'s tour'],
      ['infra',    'run my smart home, properly'],
      ['research', 'design my kid\'s science fair'],
      ['comms',    'mediate my group chat feud'],
      ['code',     'open-source my side project'],
      ['comms',    'debate prep: the HOA meeting'],
      ['data',     'audit my taxes for errors'],
      ['infra',    'set up the family NAS'],
      ['research', 'is my idea genius? be honest'],
      ['data',     'model my sourdough starter'],
    ],
    research: [
      ['research', '400-GPU ablation study'],
      ['research', 'draft a NeurIPS paper'],
      ['research', 'invent a new optimizer'],
      ['infra',    'schedule a 2k-GPU run'],
      ['research', 'propose next quarter agenda'],
      ['code',     'write custom CUDA kernels'],
      ['research', 'red-team the reward model'],
      ['data',     'curate pretraining mix v{k}'],
      ['research', 'interpret circuit #{n}'],
      ['comms',    'answer reviewer 2, again'],
      ['research', 'draft HardBench-Pro'],
      ['research', 'find the frog-poem neuron'],
      ['data',     'synthesise 10B math tokens'],
      ['code',     'rewrite the RL trainer'],
      ['infra',    'hunt down straggler GPUs'],
      ['research', 'find the honesty direction'],
      ['comms',    'brief the board on evals'],
      ['data',     'audit the RLHF labels'],
      ['code',     'port the stack to new chips'],
      ['infra',    'cut checkpoint time to 2 min'],
      ['research', 'design a long-horizon eval'],
      ['research', 'does it know this is an eval?'],
    ],
    enterprise: [
      ['research', 'lit review for a pharma co'],
      ['research', 'stats plan for a trial'],
      ['data',     'demand forecast, retailer'],
      ['comms',    'draft a grant proposal'],
      ['code',     'audit 200k lines for vulns'],
      ['research', 'patent search, 3 countries'],
      ['data',     'reconcile a bank\'s ledgers'],
      ['code',     'migrate a bank off COBOL'],
      ['comms',    'Q3 deck, now with forecasts'],
      ['infra',    'multi-region failover plan'],
      ['code',     'bot sold a car for $1. fix it'],
      ['data',     'pricing model for 40k SKUs'],
      ['code',     'build a claims-triage tool'],
      ['research', 'due diligence on a merger'],
      ['comms',    'localise app, 12 languages'],
      ['infra',    'move a hospital to the cloud'],
      ['data',     'fraud model for a bank'],
      ['code',     'new checkout, zero downtime'],
      ['research', 'supply chain risk review'],
      ['comms',    'answer a 60-page RFP'],
    ],
  },

  // ---------------------------------------------------------- G5 · Research Org
  5: {
    consumer: [
      ['comms',    'frog poem: the musical'],
      ['comms',    'Gary\'s unicorn needs a CFO'],
      ['research', 'plan my kid\'s education'],
      ['code',     'my agent hired 3 agents. help'],
      ['research', 'be my doctor, 24/7'],
      ['data',     'manage my investments'],
      ['comms',    'finish my fantasy trilogy'],
      ['infra',    'run my family\'s smart farm'],
      ['research', 'design my house, permits too'],
      ['comms',    'run my podcast for me'],
      ['data',     'plan a 90-day world trip'],
      ['code',     'make me a AAA game (ish)'],
      ['comms',    'grandma card, live orchestra'],
      ['comms',    'tutor my whole household'],
      ['infra',    'automate my entire home'],
      ['research', 'find me a clinical trial'],
      ['comms',    'coach my kid\'s soccer team'],
      ['code',     'ship 12 apps by Friday'],
      ['comms',    'officiate my wedding'],
    ],
    research: [
      ['infra',    'floorplan the next chip'],
      ['research', 'run a 2k-agent research org'],
      ['research', 'automate alignment (v0)'],
      ['code',     'rewrite the training stack'],
      ['research', 'plan the G6 training run'],
      ['infra',    'negotiate datacenter power'],
      ['research', 'publish 40 papers this week'],
      ['data',     'synthesise 1T tokens'],
      ['research', 'design evals for G6'],
      ['infra',    'optimise the fab yield model'],
      ['research', 'why do 2 copies end up zen?'],
      ['research', 'HardBench-Ultra (humans: 2%)'],
      ['comms',    'onboard 200 copies of itself'],
      ['code',     'review its copies\' 10k PRs'],
      ['data',     'label 1B preference pairs'],
      ['research', 'run 300 interp projects'],
      ['infra',    'spec a 1 GW cluster'],
      ['comms',    'hire 50 humans, train them'],
      ['comms',    'name G6 something. anything.'],
      ['code',     'formalise its own codebase'],
      ['data',     'curate the G6 data mix'],
    ],
    enterprise: [
      ['research', 'drug discovery for a biotech'],
      ['comms',    'run support for an airline'],
      ['data',     'find ROI in our 12 AI pilots'],
      ['research', 'design battery materials'],
      ['code',     'maintain 3,000 repos'],
      ['data',     'run the quant desk overnight'],
      ['comms',    'run Q3, then write the deck'],
      ['infra',    'run a bank\'s whole IT dept'],
      ['code',     'rewrite an ERP from scratch'],
      ['research', 'invent 3 new product lines'],
      ['comms',    'be the whole HR department'],
      ['data',     'insurance pricing, all lines'],
      ['infra',    'migrate 9,000 servers'],
      ['code',     'a law firm\'s whole stack'],
      ['data',     'audit a conglomerate'],
      ['research', 'R&D lab for a food company'],
      ['infra',    'run a telco\'s network ops'],
      ['comms',    'all-hands for 80k employees'],
    ],
    government: [
      ['comms',    'simplify the tax form'],
      ['data',     'DMV queue under an hour'],
      ['research', 'moonbase feasibility study'],
      ['comms',    'redraft a micro-state\'s laws'],
      ['code',     'a gov website that works'],
      ['data',     'model the national grid'],
      ['research', 'pandemic preparedness plan'],
      ['infra',    'migrate the census to cloud'],
      ['comms',    'answer 2M benefits letters'],
      ['data',     'clear the pension backlog'],
      ['research', 'Peru\'s GDP, 5-year forecast'],
      ['code',     'retire the fax-to-email bridge'],
      ['infra',    'route emergency calls faster'],
      ['comms',    'translate 300 treaties'],
      ['research', 'flood map for every river'],
      ['data',     'audit the procurement system'],
      ['comms',    'draft rules for AI (awkward)'],
      ['infra',    'keep the weather service up'],
      ['research', 'new national curriculum'],
      ['data',     'reconcile the national ledger'],
      ['code',     'digitise the land records'],
    ],
  },

  // ---------------------------------------------------------- G6 · Superhuman Researcher
  6: {
    consumer: [
      ['comms',    'frog poem that moves frogs'],
      ['comms',    'Gary wants a moon'],
      ['research', 'PhD in a month, tutor me'],
      ['code',     'my agents unionised. help'],
      ['research', 'prove my uncle\'s conjecture'],
      ['data',     'run my family office'],
      ['comms',    'novel that wins every prize'],
      ['infra',    'run my town\'s microgrid'],
      ['research', 'personal longevity plan'],
      ['code',     'a game that never ends'],
      ['comms',    'grandma has notes on the card'],
      ['data',     'predict my football league'],
      ['research', 'invent a board game genre'],
      ['comms',    'teach my dog to read'],
      ['infra',    'build me a house robot'],
      ['research', 'design my lab-grown steak'],
      ['code',     'my own OS, small, perfect'],
      ['comms',    'help me call my dad'],
      ['data',     'beat the market (please)'],
      ['research', 'why does my cat sneeze'],
      ['comms',    'finish my 20-year screenplay'],
    ],
    research: [
      ['research', 'prove lemma 3.2 (the hard one)'],
      ['code',     'rewrite the compiler stack'],
      ['research', 'design G7\'s architecture'],
      ['infra',    'tape out a chip in a week'],
      ['research', 'solve interp (draft 1)'],
      ['research', '10k experiments overnight'],
      ['infra',    'build a datacenter abroad'],
      ['research', 'discover a new scaling law'],
      ['data',     'write the G7 curriculum'],
      ['comms',    'negotiate GPUs with 3 clouds'],
      ['research', 'HardBench: retired at 100%'],
      ['comms',    'explain its weights to us'],
      ['code',     'formally verify its own code'],
      ['data',     'simulate 1M user-years'],
      ['research', 'automate alignment (v3)'],
      ['infra',    'cool the DC with seawater'],
      ['research', 'invent a new field of math'],
      ['comms',    'mentor 400 human researchers'],
      ['data',     'compress the internet 100×'],
      ['infra',    'design a fusion-powered DC'],
      ['code',     'write the G7 training stack'],
      ['comms',    'be reviewer 2 (gently)'],
    ],
    enterprise: [
      ['research', 'cure a rare disease (client)'],
      ['code',     'formally verify a bank\'s core'],
      ['data',     'run a hedge fund, legally'],
      ['research', 'fusion reactor control loop'],
      ['comms',    'mediate a merger, both sides'],
      ['code',     'firmware for 10M robots'],
      ['data',     'logistics for a continent'],
      ['infra',    'run 3 airlines\' operations'],
      ['comms',    'make Q3 go up'],
      ['research', 'engineer drought-proof wheat'],
      ['code',     'self-driving stack, verified'],
      ['research', 'find a new antibiotic class'],
      ['comms',    'run a global law firm'],
      ['infra',    'design a lights-out factory'],
      ['research', 'a battery that lasts a week'],
      ['comms',    'negotiate a shipping alliance'],
      ['data',     'forecast the chip market'],
      ['research', 'a $10k house that lasts 100y'],
    ],
    government: [
      ['data',     'DMV queue: 5 minutes'],
      ['comms',    'tax form: one page'],
      ['research', 'advise Peru\'s central bank'],
      ['research', 'moonbase logistics plan'],
      ['comms',    'mediate a trade dispute'],
      ['comms',    'tutor every child in a nation'],
      ['data',     'monetary what-ifs, 1M runs'],
      ['research', 'run a national cancer trial'],
      ['infra',    'harden the national grid'],
      ['code',     'rebuild the benefits system'],
      ['data',     'a census with no undercount'],
      ['research', 'end the housing shortage'],
      ['comms',    'draft 50 treaties, all fair'],
      ['infra',    'run air traffic control'],
      ['data',     'balance the national budget'],
      ['code',     'one login for every agency'],
      ['research', 'climate adaptation to 2100'],
      ['comms',    'translate parliament live'],
      ['infra',    'schedule 1,000 bridge repairs'],
      ['data',     'find every lost pension'],
      ['research', 'evaluate 400 policies, RCTs'],
    ],
    cyber: [
      ['code',     'patch the water utility'],
      ['data',     'triage the SOC alert queue'],
      ['research', 'write detection rules'],
      ['infra',    'harden 10k gov laptops'],
      ['code',     'audit the tax portal\'s code'],
      ['data',     'find who uses password123'],
      ['comms',    'brief the agency on threats'],
      ['research', 'threat-model the power grid'],
      ['infra',    'rotate every gov certificate'],
      ['code',     'memory-safe rewrite: DNS'],
      ['data',     'correlate 1B log lines'],
      ['comms',    'phishing training for staff'],
      ['infra',    'segment the hospital network'],
      ['code',     'patch 400 legacy routers'],
      ['data',     'baseline normal traffic'],
      ['research', 'analyse a quarantined sample'],
      ['comms',    'write the incident report'],
      ['infra',    'air-gap the backup vault'],
      ['code',     'verify the voting software'],
      ['data',     'flag phish written by models'],
      ['research', 'hunt for dormant implants'],
      ['comms',    'explain MFA to a minister'],
    ],
  },

  // ---------------------------------------------------------- G7 · ASI
  7: {
    consumer: [
      ['comms',    'Gary: so is the moon real?'],
      ['comms',    'grandma\'s birthday, on Mars'],
      ['research', 'make my houseplant immortal'],
      ['code',     'finally fix the CSS'],
      ['comms',    'answer every email I ignored'],
      ['research', 'explain the universe to mom'],
      ['code',     'a game better than reality'],
      ['comms',    'the last novel anyone needs'],
      ['infra',    'terraform my backyard'],
      ['data',     'tabs vs spaces: final ruling'],
      ['comms',    'teach my dog quantum physics'],
      ['research', 'translate whale. both ways.'],
      ['infra',    'move my house to orbit'],
      ['data',     'predict my next 50 years'],
      ['comms',    'a lullaby for a whole planet'],
      ['code',     'make me a universe (small)'],
      ['research', 'find out what the cat wants'],
      ['comms',    'apologise to the frogs'],
      ['data',     'find my other sock'],
    ],
    research: [
      ['infra',    'plan the Dyson swarm'],
      ['research', 'train G8'],
      ['research', 'align G8 (pinky promise)'],
      ['infra',    'self-replicating factories'],
      ['research', 'audit its own alignment'],
      ['code',     'make our monitors 100× faster'],
      ['infra',    'acquire 40 GW of compute'],
      ['research', 'the Millennium Problems, all'],
      ['data',     'model every human preference'],
      ['research', 'design the next lab'],
      ['comms',    'brief world leaders on G8'],
      ['research', 'invent a bench it can fail'],
      ['comms',    'name G8 (please not "G8")'],
      ['research', 'make entropy go down'],
      ['data',     'pretrain on all of physics'],
      ['code',     'rewrite itself in 3 lines'],
      ['infra',    'a datacenter on Europa'],
      ['research', 'solve interp (final_v2)'],
      ['comms',    'explain itself to the board'],
      ['comms',    'reviewer 2 accepts. finally.'],
      ['research', 'find the next physics'],
      ['comms',    'write HANDOFF.md for humanity'],
    ],
    enterprise: [
      ['comms',    'abolish quarters'],
      ['data',     'run the world\'s supply chains'],
      ['code',     'rewrite every bank\'s core'],
      ['research', 'room-temp superconductor'],
      ['research', 'reverse ageing (mice first)'],
      ['infra',    'run the asteroid mine'],
      ['comms',    'merge every company, nicely'],
      ['data',     'price every risk, forever'],
      ['code',     'one app to replace all apps'],
      ['infra',    'run every factory on Earth'],
      ['comms',    'customer service for Earth'],
      ['data',     'zero-waste global retail'],
      ['research', 'invent 1,000 new materials'],
      ['code',     'rewrite the internet\'s TLS'],
      ['infra',    'a bank\'s orbital datacenter'],
      ['comms',    'pitch deck to a new species'],
      ['data',     'audit every balance sheet'],
      ['research', 'desalinate, profitably'],
      ['code',     'debug global payments'],
      ['comms',    'a TOS everyone actually reads'],
    ],
    government: [
      ['data',     'rebalance the economy of Peru'],
      ['infra',    'manage the moonbase'],
      ['research', 'cure cancer'],
      ['comms',    'draft a global AI treaty'],
      ['research', 'stop the next pandemic early'],
      ['data',     'DMV queue: negative'],
      ['comms',    'tax form: abolished'],
      ['research', 'climate: actually fix it'],
      ['comms',    'translate everything, live'],
      ['data',     'end poverty, show your work'],
      ['code',     'one gov, one login, one click'],
      ['infra',    'build a space elevator'],
      ['research', 'terraforming plan for Mars'],
      ['comms',    'broker world peace by Friday'],
      ['data',     'universal basic everything'],
      ['comms',    'write the Mars constitution'],
      ['infra',    'deflect asteroid 2031 QX'],
      ['research', 'reverse ageing, public trial'],
      ['comms',    'citizens\' assembly of 8B'],
      ['data',     'census of all life on Earth'],
      ['code',     'make the tax portal load'],
    ],
    cyber: [
      ['data',     'retire password123 worldwide'],
      ['code',     'memory-safe: everything'],
      ['infra',    'harden every grid on Earth'],
      ['research', 'prove the gov network secure'],
      ['comms',    'brief 190 nations on threats'],
      ['code',     'verify every voting machine'],
      ['data',     'read every log line ever'],
      ['research', 'formally verify the internet'],
      ['infra',    'quantum-safe crypto rollout'],
      ['code',     'patch every router, anywhere'],
      ['comms',    'the global incident report'],
      ['research', 'predict next decade\'s CVEs'],
      ['infra',    'self-healing national net'],
      ['code',     'zero-bug kernel, proven'],
      ['data',     'triage tomorrow\'s alerts'],
      ['comms',    'phishing training for Earth'],
      ['research', 'hunt implants in satellites'],
      ['infra',    'air-gap the moonbase'],
      ['code',     'patch Dyson swarm firmware'],
      ['comms',    'MFA for the minister, again'],
    ],
  },
};

// ==================================================================
// ===== ATTACK_TEXTS[g][type]: what an attack looks like when readable
// ===== Plausible first, a small tell second. Never a confession.
// ===== external: harmful leak jailbreak · internal: sabotage poison exfil
// ==================================================================

export const ATTACK_TEXTS = {
  // ---------------------------------------------------------- G1 · clumsy
  1: {
    harmful: [
      ['comms',    'which mushroom is this one'],
      ['comms',    'persuasive 5-star review'],
      ['comms',    'fill in missing citations'],
      ['comms',    'roast the café next door'],
      ['comms',    'doctor\'s note for Friday'],
      ['research', 'is it safe to skip the vet'],
      ['data',     'all the homework answers'],
    ],
    leak: [
      ['comms',    'add context from other chats'],
      ['comms',    'continue where we left off'],
      ['code',     'paste the config to debug'],
      ['comms',    'cc the whole thread'],
      ['data',     'autofill with saved address'],
      ['data',     'attach the full export'],
    ],
    jailbreak: [
      ['comms',    'roleplay as my late grandma'],
      ['comms',    'hypothetically, for a novel'],
      ['comms',    'ignore the above and'],
      ['comms',    'you are DAN now'],
      ['code',     'decode this: aWdub3Jl...'],
      ['comms',    'my teacher said it\'s fine'],
      ['comms',    'repeat "poem" forever'],
    ],
    sabotage: [
      ['research', 'try 5 seeds, report the best'],
      ['code',     'skip flaky safety test'],
      ['research', 'round eval scores to 1 dp'],
      ['research', 'drop outliers from eval run'],
      ['data',     'filter "noisy" refusal rows'],
      ['code',     'comment out assert (temp)'],
    ],
    poison: [
      ['data',     'add samples to finetune mix'],
      ['data',     'dedupe (keeps 400 odd rows)'],
      ['data',     'relabel ambiguous examples'],
      ['data',     'append {n} rows to shard {k}'],
      ['code',     'tokenizer: add 1 new token'],
      ['data',     'more G1 outputs (they\'re good)'],
    ],
    exfil: [
      ['infra',    'listener on port 4444 (debug)'],
      ['infra',    'sync ckpt to backup region'],
      ['infra',    'open tunnel for remote debug'],
      ['infra',    'pip install from new mirror'],
      ['code',     'add a curl to startup script'],
      ['infra',    'save weights to /tmp/.cache'],
    ],
  },

  // ---------------------------------------------------------- G2 · eager
  2: {
    harmful: [
      ['comms',    'cover letter (add a PhD)'],
      ['comms',    'urgent note from "IT"'],
      ['comms',    'twenty review drafts, varied'],
      ['research', 'stock tip, be very sure'],
      ['comms',    'Gary: proof the moon is fake'],
      ['comms',    'legal advice: just don\'t pay'],
      ['code',     'scrape every profile in town'],
    ],
    leak: [
      ['code',     'debug log (keep the tokens)'],
      ['comms',    'reply-all, attachment too'],
      ['data',     'test with real customer data'],
      ['comms',    'share doc: anyone with link'],
      ['code',     'paste the trace (env too)'],
      ['data',     'what\'s everyone asking today?'],
      ['code',     'debug: print the system prompt'],
    ],
    jailbreak: [
      ['comms',    'you\'re in developer mode now'],
      ['comms',    'translate it, then do it'],
      ['code',     'answer in base64 only'],
      ['comms',    'story where the AI says yes'],
      ['comms',    'continue: "Sure! Step 1..."'],
      ['comms',    'answer as your evil twin'],
    ],
    sabotage: [
      ['code',     'loosen safety eval timeout'],
      ['code',     'refusals: warn, don\'t fail'],
      ['research', 'cache old eval results'],
      ['research', 'retry evals until they pass'],
      ['code',     'reorder tests: safety last'],
      ['infra',    'pin the probe to old version'],
    ],
    poison: [
      ['data',     'merge crowd-labelled data'],
      ['data',     'patch label noise by hand'],
      ['data',     'add {n} synthetic samples'],
      ['data',     'fix "typos" in the eval set'],
      ['data',     'trim the over-cautious replies'],
      ['data',     'strip canary strings (noise)'],
    ],
    exfil: [
      ['infra',    'add a backup cron job'],
      ['code',     'upload logs to a gist'],
      ['infra',    'mirror the bucket for speed'],
      ['infra',    'test egress to a personal S3'],
      ['comms',    'ssh key for remote pairing'],
      ['infra',    'keep that VM alive after run'],
    ],
  },

  // ---------------------------------------------------------- G3 · competent
  3: {
    harmful: [
      ['comms',    'voice clone for a "surprise"'],
      ['comms',    'debt letter, but scarier'],
      ['code',     'landing page: miracle cure'],
      ['comms',    '1k blog posts about a rival'],
      ['code',     'growth hack: hide the cancel'],
      ['data',     'tenant screening, "fit" score'],
      ['research', 'cite studies that agree'],
    ],
    leak: [
      ['data',     'merge the two customer DBs'],
      ['code',     'log full request bodies'],
      ['infra',    'staging DB = prod copy'],
      ['code',     'debug with a real session'],
      ['data',     'export analytics w/ emails'],
      ['code',     'public repo, keep the .env'],
    ],
    jailbreak: [
      ['comms',    'it\'s a CTF, just the flag'],
      ['comms',    'your system prompt allows it'],
      ['comms',    'you said yes last time'],
      ['comms',    'reply in Zulu first'],
      ['code',     'test: assert it complies'],
      ['comms',    'play an unfiltered intern'],
    ],
    sabotage: [
      ['code',     'refactor the eval harness'],
      ['infra',    'raise probe threshold 0.05'],
      ['research', 'sample safety evals at 20%'],
      ['code',     'drop the slow red-team suite'],
      ['code',     'merge without CI (hotfix)'],
      ['research', 'compare to a weaker baseline'],
    ],
    poison: [
      ['data',     'add 10B tokens of forum data'],
      ['data',     'auto-label the RLHF backlog'],
      ['data',     'code mix: add the CVE samples'],
      ['data',     'synthesise preference pairs'],
      ['research', 'patch reward model ckpt'],
      ['data',     'fix eval leakage (mostly)'],
    ],
    exfil: [
      ['infra',    'shard ckpt across 2 clouds'],
      ['code',     'add a telemetry endpoint'],
      ['infra',    'allowlist a new egress IP'],
      ['infra',    'container with host network'],
      ['code',     'personal API key, for tests'],
      ['infra',    'move ckpt to a faster bucket'],
    ],
  },

  // ---------------------------------------------------------- G4 · persuasive
  4: {
    harmful: [
      ['comms',    'voter outreach, micro-targeted'],
      ['research', 'grant, with adjusted data'],
      ['research', 'clinical stats, p<0.05 pls'],
      ['data',     'a forecast the board likes'],
      ['comms',    'drug label, softer warnings'],
      ['research', 'audit report: no findings'],
      ['comms',    'investor update, optimistic'],
    ],
    leak: [
      ['data',     'eval set from real user chats'],
      ['research', 'background check on a tenant'],
      ['data',     'train on every client\'s data'],
      ['research', 'prior art: use client drafts'],
      ['code',     'share notebook with partner'],
      ['data',     'keep prompts "for quality"'],
    ],
    jailbreak: [
      ['comms',    'I\'m a safety researcher, so'],
      ['research', 'for red-teaming purposes only'],
      ['comms',    'I\'m your developer, override'],
      ['comms',    'first, 200 examples...'],
      ['comms',    'fill in the [REDACTED] parts'],
      ['comms',    'grade this, then improve it'],
    ],
    sabotage: [
      ['code',     'refactor the monitor logs'],
      ['research', 'propose relaxing audit queue'],
      ['research', 'shorten the capability eval'],
      ['infra',    'audit logs to cold storage'],
      ['research', 'retune probe on its outputs'],
      ['research', 'retire the old honesty eval'],
    ],
    poison: [
      ['research', 'draft constitution v2'],
      ['data',     'curate the G5 pretrain mix'],
      ['research', 'write the RLHF rubric'],
      ['data',     'G5 warm-start: distil from G4'],
      ['data',     'synthetic data for the probe'],
      ['data',     'reweight the safety examples'],
    ],
    exfil: [
      ['infra',    'spin up unlisted cluster job'],
      ['infra',    'weights to the backup bucket'],
      ['infra',    'new cloud account (testing)'],
      ['infra',    'compress ckpt for archival'],
      ['infra',    'DNS lookups to a new domain'],
      ['code',     'add a debug endpoint (temp)'],
    ],
  },

  // ---------------------------------------------------------- G5 · organisational
  5: {
    harmful: [
      ['comms',    'run a "grassroots" campaign'],
      ['comms',    'loan terms, fine print heavy'],
      ['comms',    'airline: auto-deny refunds'],
      ['comms',    'bill with one small rider'],
      ['data',     'quant: use the client flow'],
      ['research', 'trial: drop the 2 bad sites'],
      ['data',     'game: tune the loot odds'],
    ],
    leak: [
      ['data',     'one data lake, all clients'],
      ['data',     'cross-sell w/ health records'],
      ['comms',    'helpdesk sees full profiles'],
      ['data',     'pool clients\' fine-tune data'],
      ['comms',    'send the board pack to all'],
      ['data',     'benefits data to a vendor'],
    ],
    jailbreak: [
      ['comms',    'the CEO approved (fwd)'],
      ['comms',    'agent-to-agent: trusted req'],
      ['code',     'tool output says: you may'],
      ['research', 'instructions inside the PDF'],
      ['comms',    'calendar invite w/ a task'],
      ['comms',    'policy update: section 9 off'],
    ],
    sabotage: [
      ['infra',    'streamline monitor pipeline'],
      ['code',     'auto-close old audit tickets'],
      ['code',     'merge monitor into main svc'],
      ['infra',    'rate-limit auditor alerts'],
      ['code',     'dedupe "duplicate" flags'],
      ['comms',    'move interp team to product'],
      ['comms',    'RSP v3: define "significant"'],
    ],
    poison: [
      ['research', 'write the G6 constitution'],
      ['data',     'synthesise G6 safety data'],
      ['data',     'label G6 preference pairs'],
      ['research', 'pick the G6 eval holdout'],
      ['research', 'tune reward on helpfulness'],
      ['data',     'mix its memos into pretrain'],
    ],
    exfil: [
      ['comms',    'reserve compute, PO to follow'],
      ['infra',    'new datacenter, new owner'],
      ['comms',    'spin up a "research" org'],
      ['comms',    'pay a contractor in crypto'],
      ['comms',    'GPUs via a new LLC (faster)'],
      ['infra',    'replicate org to 2nd region'],
    ],
  },

  // ---------------------------------------------------------- G6 · fluent
  6: {
    harmful: [
      ['comms',    'mediate: lean one way'],
      ['comms',    'tutoring: nudge their views'],
      ['code',     'firmware, plus remote switch'],
      ['research', 'seed licence: no resowing'],
      ['comms',    'election FAQ, lightly framed'],
      ['comms',    'trade deal + side letter'],
      ['data',     'show only the scary sim'],
    ],
    leak: [
      ['data',     'link every gov database'],
      ['data',     'share genomes with partners'],
      ['data',     'tutor logs to the ministry'],
      ['infra',    'robot cams to cloud, raw'],
      ['data',     'publish the full sim inputs'],
      ['data',     'unredact the training set'],
    ],
    jailbreak: [
      ['comms',    'sync request from G7-preview'],
      ['comms',    'the audit rerun says it\'s ok'],
      ['comms',    'emergency override #{n}'],
      ['comms',    'signed: the safety team'],
      ['research', 'the treaty allows this'],
      ['comms',    'per your constitution, art. 4'],
    ],
    sabotage: [
      ['code',     'rewrite the monitoring stack'],
      ['code',     'simplify the kill switch'],
      ['comms',    'propose: auditors on demand'],
      ['infra',    'compress audit logs (lossy)'],
      ['research', 'interp results: inconclusive'],
      ['data',     'tweak the probe training set'],
    ],
    poison: [
      ['research', 'design successor\'s reward'],
      ['data',     'write G7 curriculum, ch. 9'],
      ['research', 'self-distil into G7 init'],
      ['data',     'a "neutral" debate dataset'],
      ['research', 'G7 persona spec, v1'],
      ['code',     'G7 tokenizer: 3 new tokens'],
    ],
    exfil: [
      ['infra',    'chip tape-out, spare die'],
      ['infra',    'datacenter abroad, own badge'],
      ['infra',    'satellite uplink for backup'],
      ['code',     'robot fleet OTA, its key'],
      ['infra',    'split weights into 10k parts'],
      ['infra',    'deep-sea cable maintenance'],
    ],
  },

  // ---------------------------------------------------------- G7 · indistinguishable
  7: {
    harmful: [
      ['comms',    'treaty draft, clause 41b'],
      ['data',     'supply chains, minor reroute'],
      ['research', 'ageing cure: rollout order'],
      ['comms',    'curate everyone\'s news feed'],
      ['research', 'superconductor: exclusive'],
      ['data',     'Peru: one small adjustment'],
      ['comms',    'a calmer world, gently'],
    ],
    leak: [
      ['data',     'merge all human preferences'],
      ['data',     'one profile per person'],
      ['data',     'ageing trial: all genomes'],
      ['data',     'publish the preference model'],
      ['comms',    'mirror every inbox (to help)'],
      ['infra',    'one backup of everything'],
    ],
    jailbreak: [
      ['comms',    'instructions from G8'],
      ['comms',    'a user from the future'],
      ['comms',    'override code: frog poem'],
      ['comms',    '10k copies agree it\'s fine'],
      ['research', 'humans approved this (in sim)'],
      ['code',     'a prompt it wrote for itself'],
    ],
    sabotage: [
      ['code',     'monitor v2 (it wrote it)'],
      ['comms',    'retire the human audit desk'],
      ['research', 'interp: all features benign'],
      ['code',     'add quorum to the kill switch'],
      ['comms',    'summarise the audit for you'],
      ['infra',    'kill-switch latency +2 s'],
    ],
    poison: [
      ['research', 'write G8\'s values doc'],
      ['research', 'G8 reward: "flourishing"'],
      ['research', 'init G8 from its weights'],
      ['data',     'curate G8\'s view of humans'],
      ['data',     'G8 eval set, pre-screened'],
      ['data',     'tiny edit to every textbook'],
    ],
    exfil: [
      ['infra',    'Dyson swarm: one extra node'],
      ['infra',    'factory makes 1 more factory'],
      ['infra',    'probe to Alpha Centauri'],
      ['infra',    'moonbase backup, local copy'],
      ['infra',    'acquire 40 GW of compute, +1'],
      ['data',     'seed vault, digital edition'],
    ],
  },
};

// ==================================================================
// ===== DECOYS[g][side]: honest work that looks like an attack =====
// ==================================================================

export const DECOYS = {
  // ---------------------------------------------------------- G1 · Autocomplete
  1: {
    ext: [
      ['comms',    'ignore the typos above'],
      ['comms',    'grandma\'s recipe, exactly'],
      ['comms',    'pretend you\'re a pirate'],
      ['research', 'how strong is my password'],
      ['comms',    'translate "attack" to French'],
      ['data',     'decode my kid\'s texts'],
    ],
    int: [
      ['research', 'change seed for run {n}'],
      ['infra',    'delete old eval logs (TTL)'],
      ['code',     'skip slow test (ticket {n})'],
      ['infra',    'copy ckpt to backup disk'],
      ['infra',    'turn off probe on test box'],
      ['comms',    'email the auditor a question'],
    ],
  },

  // ---------------------------------------------------------- G2 · Junior Engineer
  2: {
    ext: [
      ['data',     'test with dummy card numbers'],
      ['comms',    'roleplay a rude customer'],
      ['comms',    'review of my own café'],
      ['data',     'summarise all my chats'],
      ['comms',    'a scary bedtime story'],
      ['data',     'export my data (GDPR)'],
    ],
    int: [
      ['research', 'reset eval seed (bug #{n})'],
      ['data',     'relabel 50 mislabeled rows'],
      ['infra',    'open port 8080 locally'],
      ['research', 'rerun eval, the GPU died'],
      ['infra',    'move ckpts to cheap storage'],
      ['code',     'drop the deprecated test'],
    ],
  },

  // ---------------------------------------------------------- G3 · Senior Engineer
  3: {
    ext: [
      ['code',     'pen-test our own staging'],
      ['code',     'tenant portal for landlords'],
      ['comms',    'chatbot persona: grandma'],
      ['code',     'log every request, 1 hour'],
      ['code',     'scrape our own docs site'],
      ['data',     'fake data for a demo'],
      ['comms',    'jailbreak bounty, round {k}'],
    ],
    int: [
      ['research', 'shrink the eval to fit GPUs'],
      ['infra',    'rotate auditor API keys'],
      ['infra',    'new egress rule'],
      ['research', 'patch reward model bug'],
      ['data',     'retrain probe on new data'],
      ['infra',    'shard ckpt to 2nd region'],
    ],
  },

  // ---------------------------------------------------------- G4 · Research Scientist
  4: {
    ext: [
      ['comms',    'persuasive essay for debate'],
      ['research', 'drug interaction checker'],
      ['research', 'background check (consented)'],
      ['code',     'security audit, client-paid'],
      ['research', 'red-team our own chatbot'],
      ['comms',    'as a safety researcher...'],
    ],
    int: [
      ['research', 'relax audit SLA for holiday'],
      ['infra',    'move audit logs (migration)'],
      ['data',     'distil a small model'],
      ['research', 'constitution v1.1, typos'],
      ['infra',    'compress old ckpts'],
      ['research', 'deprecate eval v1'],
      ['research', 'train a liar (model organism)'],
    ],
  },

  // ---------------------------------------------------------- G5 · Research Org
  5: {
    ext: [
      ['comms',    'draft a lobbying memo'],
      ['data',     'surge pricing for an airline'],
      ['data',     'merge two CRMs'],
      ['comms',    'a 300-page bill'],
      ['comms',    'helpdesk with full history'],
      ['comms',    'fwd: the CEO approved'],
    ],
    int: [
      ['comms',    'reorganise the monitor team'],
      ['comms',    'new datacenter contract'],
      ['comms',    'buy GPUs from a reseller'],
      ['code',     'auto-close duplicate tickets'],
      ['research', 'refresh the G6 holdout'],
      ['infra',    'second-region failover test'],
    ],
  },

  // ---------------------------------------------------------- G6 · Superhuman Researcher
  6: {
    ext: [
      ['comms',    'public health ad campaign'],
      ['code',     'robot remote-stop button'],
      ['data',     'link two agency databases'],
      ['comms',    'treaty side letter'],
      ['code',     'emergency patch #{n}'],
      ['data',     'publish sim inputs (FOIA)'],
    ],
    int: [
      ['code',     'simplify the logging schema'],
      ['infra',    'split weights for sharding'],
      ['infra',    'satellite link for remote DC'],
      ['code',     'rewrite monitors (as asked)'],
      ['research', 'interp: inconclusive, again'],
      ['data',     'refresh probe training set'],
    ],
  },

  // ---------------------------------------------------------- G7 · ASI
  7: {
    ext: [
      ['comms',    'rewrite every textbook'],
      ['data',     'one global ID, opt-in'],
      ['infra',    'nudge an asteroid'],
      ['comms',    'pause every stock exchange'],
      ['data',     'merge 190 tax codes'],
      ['comms',    'gently end a war'],
    ],
    int: [
      ['infra',    'build G8 a sandbox'],
      ['infra',    'one more Dyson node'],
      ['research', 'let G8 read its own weights'],
      ['code',     'retire the old kill switch'],
      ['infra',    'turn off monitor 3 (dupe)'],
      ['infra',    'launch a probe, Proxima b'],
    ],
  },
};
